<?php

declare(strict_types=1);

// 由 tools/build-language-names.js 生成（CLDR 语言名称），勿手改；注册表增删语言后重跑。
// 界面语言 => [语言代码 => 该界面语言里的名称]
return [
    'zh-CN' => ['zh-CN' => '中文（简体）', 'zh-TW' => '中文（繁体）', 'en' => '英语', 'ja' => '日语', 'ko' => '韩语', 'es' => '西班牙语', 'pt' => '葡萄牙语（巴西）', 'fr' => '法语', 'de' => '德语', 'ru' => '俄语', 'it' => '意大利语', 'tr' => '土耳其语', 'vi' => '越南语', 'id' => '印度尼西亚语', 'th' => '泰语', 'ar' => '阿拉伯语', 'fa' => '波斯语', 'ms' => '马来语'],
    'zh-TW' => ['zh-CN' => '中文（簡體）', 'zh-TW' => '中文（繁體）', 'en' => '英文', 'ja' => '日文', 'ko' => '韓文', 'es' => '西班牙文', 'pt' => '葡萄牙文（巴西）', 'fr' => '法文', 'de' => '德文', 'ru' => '俄文', 'it' => '義大利文', 'tr' => '土耳其文', 'vi' => '越南文', 'id' => '印尼文', 'th' => '泰文', 'ar' => '阿拉伯文', 'fa' => '波斯文', 'ms' => '馬來文'],
    'en' => ['zh-CN' => 'Chinese (Simplified)', 'zh-TW' => 'Chinese (Traditional)', 'en' => 'English', 'ja' => 'Japanese', 'ko' => 'Korean', 'es' => 'Spanish', 'pt' => 'Portuguese (Brazil)', 'fr' => 'French', 'de' => 'German', 'ru' => 'Russian', 'it' => 'Italian', 'tr' => 'Turkish', 'vi' => 'Vietnamese', 'id' => 'Indonesian', 'th' => 'Thai', 'ar' => 'Arabic', 'fa' => 'Persian', 'ms' => 'Malay'],
    'ja' => ['zh-CN' => '中国語 (簡体字)', 'zh-TW' => '中国語 (繁体字)', 'en' => '英語', 'ja' => '日本語', 'ko' => '韓国語', 'es' => 'スペイン語', 'pt' => 'ポルトガル語 (ブラジル)', 'fr' => 'フランス語', 'de' => 'ドイツ語', 'ru' => 'ロシア語', 'it' => 'イタリア語', 'tr' => 'トルコ語', 'vi' => 'ベトナム語', 'id' => 'インドネシア語', 'th' => 'タイ語', 'ar' => 'アラビア語', 'fa' => 'ペルシア語', 'ms' => 'マレー語'],
    'ko' => ['zh-CN' => '중국어(간체)', 'zh-TW' => '중국어(번체)', 'en' => '영어', 'ja' => '일본어', 'ko' => '한국어', 'es' => '스페인어', 'pt' => '포르투갈어(브라질)', 'fr' => '프랑스어', 'de' => '독일어', 'ru' => '러시아어', 'it' => '이탈리아어', 'tr' => '튀르키예어', 'vi' => '베트남어', 'id' => '인도네시아어', 'th' => '태국어', 'ar' => '아랍어', 'fa' => '페르시아어', 'ms' => '말레이어'],
    'es' => ['zh-CN' => 'chino (simplificado)', 'zh-TW' => 'chino (tradicional)', 'en' => 'inglés', 'ja' => 'japonés', 'ko' => 'coreano', 'es' => 'español', 'pt' => 'portugués (Brasil)', 'fr' => 'francés', 'de' => 'alemán', 'ru' => 'ruso', 'it' => 'italiano', 'tr' => 'turco', 'vi' => 'vietnamita', 'id' => 'indonesio', 'th' => 'tailandés', 'ar' => 'árabe', 'fa' => 'persa', 'ms' => 'malayo'],
    'pt' => ['zh-CN' => 'chinês (simplificado)', 'zh-TW' => 'chinês (tradicional)', 'en' => 'inglês', 'ja' => 'japonês', 'ko' => 'coreano', 'es' => 'espanhol', 'pt' => 'português (Brasil)', 'fr' => 'francês', 'de' => 'alemão', 'ru' => 'russo', 'it' => 'italiano', 'tr' => 'turco', 'vi' => 'vietnamita', 'id' => 'indonésio', 'th' => 'tailandês', 'ar' => 'árabe', 'fa' => 'persa', 'ms' => 'malaio'],
    'fr' => ['zh-CN' => 'chinois (simplifié)', 'zh-TW' => 'chinois (traditionnel)', 'en' => 'anglais', 'ja' => 'japonais', 'ko' => 'coréen', 'es' => 'espagnol', 'pt' => 'portugais (Brésil)', 'fr' => 'français', 'de' => 'allemand', 'ru' => 'russe', 'it' => 'italien', 'tr' => 'turc', 'vi' => 'vietnamien', 'id' => 'indonésien', 'th' => 'thaï', 'ar' => 'arabe', 'fa' => 'persan', 'ms' => 'malais'],
    'de' => ['zh-CN' => 'Chinesisch (Vereinfacht)', 'zh-TW' => 'Chinesisch (Traditionell)', 'en' => 'Englisch', 'ja' => 'Japanisch', 'ko' => 'Koreanisch', 'es' => 'Spanisch', 'pt' => 'Portugiesisch (Brasilien)', 'fr' => 'Französisch', 'de' => 'Deutsch', 'ru' => 'Russisch', 'it' => 'Italienisch', 'tr' => 'Türkisch', 'vi' => 'Vietnamesisch', 'id' => 'Indonesisch', 'th' => 'Thailändisch', 'ar' => 'Arabisch', 'fa' => 'Persisch', 'ms' => 'Malaiisch'],
    'ru' => ['zh-CN' => 'китайский (упрощенная)', 'zh-TW' => 'китайский (традиционная)', 'en' => 'английский', 'ja' => 'японский', 'ko' => 'корейский', 'es' => 'испанский', 'pt' => 'португальский (Бразилия)', 'fr' => 'французский', 'de' => 'немецкий', 'ru' => 'русский', 'it' => 'итальянский', 'tr' => 'турецкий', 'vi' => 'вьетнамский', 'id' => 'индонезийский', 'th' => 'тайский', 'ar' => 'арабский', 'fa' => 'персидский', 'ms' => 'малайский'],
    'it' => ['zh-CN' => 'cinese (semplificato)', 'zh-TW' => 'cinese (tradizionale)', 'en' => 'inglese', 'ja' => 'giapponese', 'ko' => 'coreano', 'es' => 'spagnolo', 'pt' => 'portoghese (Brasile)', 'fr' => 'francese', 'de' => 'tedesco', 'ru' => 'russo', 'it' => 'italiano', 'tr' => 'turco', 'vi' => 'vietnamita', 'id' => 'indonesiano', 'th' => 'thailandese', 'ar' => 'arabo', 'fa' => 'persiano', 'ms' => 'malese'],
    'tr' => ['zh-CN' => 'Çince (Basitleştirilmiş)', 'zh-TW' => 'Çince (Geleneksel)', 'en' => 'İngilizce', 'ja' => 'Japonca', 'ko' => 'Korece', 'es' => 'İspanyolca', 'pt' => 'Portekizce (Brezilya)', 'fr' => 'Fransızca', 'de' => 'Almanca', 'ru' => 'Rusça', 'it' => 'İtalyanca', 'tr' => 'Türkçe', 'vi' => 'Vietnamca', 'id' => 'Endonezce', 'th' => 'Tayca', 'ar' => 'Arapça', 'fa' => 'Farsça', 'ms' => 'Malayca'],
    'vi' => ['zh-CN' => 'Tiếng Trung (Giản thể)', 'zh-TW' => 'Tiếng Trung (Phồn thể)', 'en' => 'Tiếng Anh', 'ja' => 'Tiếng Nhật', 'ko' => 'Tiếng Hàn', 'es' => 'Tiếng Tây Ban Nha', 'pt' => 'Tiếng Bồ Đào Nha (Brazil)', 'fr' => 'Tiếng Pháp', 'de' => 'Tiếng Đức', 'ru' => 'Tiếng Nga', 'it' => 'Tiếng Italy', 'tr' => 'Tiếng Thổ Nhĩ Kỳ', 'vi' => 'Tiếng Việt', 'id' => 'Tiếng Indonesia', 'th' => 'Tiếng Thái', 'ar' => 'Tiếng Ả Rập', 'fa' => 'Tiếng Ba Tư', 'ms' => 'Tiếng Mã Lai'],
    'id' => ['zh-CN' => 'Tionghoa (Sederhana)', 'zh-TW' => 'Tionghoa (Tradisional)', 'en' => 'Inggris', 'ja' => 'Jepang', 'ko' => 'Korea', 'es' => 'Spanyol', 'pt' => 'Portugis (Brasil)', 'fr' => 'Prancis', 'de' => 'Jerman', 'ru' => 'Rusia', 'it' => 'Italia', 'tr' => 'Turki', 'vi' => 'Vietnam', 'id' => 'Indonesia', 'th' => 'Thai', 'ar' => 'Arab', 'fa' => 'Persia', 'ms' => 'Melayu'],
    'th' => ['zh-CN' => 'จีน (ตัวย่อ)', 'zh-TW' => 'จีน (ตัวเต็ม)', 'en' => 'อังกฤษ', 'ja' => 'ญี่ปุ่น', 'ko' => 'เกาหลี', 'es' => 'สเปน', 'pt' => 'โปรตุเกส (บราซิล)', 'fr' => 'ฝรั่งเศส', 'de' => 'เยอรมัน', 'ru' => 'รัสเซีย', 'it' => 'อิตาลี', 'tr' => 'ตุรกี', 'vi' => 'เวียดนาม', 'id' => 'อินโดนีเซีย', 'th' => 'ไทย', 'ar' => 'อาหรับ', 'fa' => 'เปอร์เซีย', 'ms' => 'มาเลย์'],
    'ar' => ['zh-CN' => 'الصينية (المبسطة)', 'zh-TW' => 'الصينية (التقليدية)', 'en' => 'الإنجليزية', 'ja' => 'اليابانية', 'ko' => 'الكورية', 'es' => 'الإسبانية', 'pt' => 'البرتغالية (البرازيل)', 'fr' => 'الفرنسية', 'de' => 'الألمانية', 'ru' => 'الروسية', 'it' => 'الإيطالية', 'tr' => 'التركية', 'vi' => 'الفيتنامية', 'id' => 'الإندونيسية', 'th' => 'التايلاندية', 'ar' => 'العربية', 'fa' => 'الفارسية', 'ms' => 'الماليزية'],
    'fa' => ['zh-CN' => 'چینی (ساده‌شده)', 'zh-TW' => 'چینی (سنتی)', 'en' => 'انگلیسی', 'ja' => 'ژاپنی', 'ko' => 'کره‌ای', 'es' => 'اسپانیایی', 'pt' => 'پرتغالی (برزیل)', 'fr' => 'فرانسوی', 'de' => 'آلمانی', 'ru' => 'روسی', 'it' => 'ایتالیایی', 'tr' => 'ترکی استانبولی', 'vi' => 'ویتنامی', 'id' => 'اندونزیایی', 'th' => 'تایلندی', 'ar' => 'عربی', 'fa' => 'فارسی', 'ms' => 'مالایی'],
    'ms' => ['zh-CN' => 'Cina (Ringkas)', 'zh-TW' => 'Cina (Tradisional)', 'en' => 'Inggeris', 'ja' => 'Jepun', 'ko' => 'Korea', 'es' => 'Sepanyol', 'pt' => 'Portugis (Brazil)', 'fr' => 'Perancis', 'de' => 'Jerman', 'ru' => 'Rusia', 'it' => 'Itali', 'tr' => 'Turki', 'vi' => 'Vietnam', 'id' => 'Indonesia', 'th' => 'Thai', 'ar' => 'Arab', 'fa' => 'Parsi', 'ms' => 'Melayu'],
];
