<?php
/**
 * YikaiCMS - Arabic language pack (ar).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'pcar_block_name' => 'سلايدر المنتجات',
    'pcar_f_title' => 'العنوان',
    'pcar_title_ph' => 'مثلًا: المنتجات المميزة',
    'pcar_per_screen' => 'عدد العناصر في العرض الواحد',
    'pcar_autoplay' => 'التشغيل التلقائي',
    'pcar_on' => 'تشغيل',
    'pcar_interval' => 'الفاصل الزمني (بالثواني)',
    'pcar_selected' => 'المنتجات المحددة (ترتيب العرض؛ استخدم الأسهم لإعادة الترتيب)',
    'pcar_item_fallback' => 'المنتج #',
    'pcar_none_selected' => 'لم يتم اختيار منتجات بعد',
    'pcar_batch_add' => 'إضافة دفعة',
    'pcar_search_ph' => 'تصفية حسب اسم المنتج…',
    'pcar_no_published' => 'لا توجد منتجات منشورة',
    'pcar_add_checked' => 'إضافة المحدد',
    'pcar_prev_group' => 'السابق',
    'pcar_next_group' => 'التالي',
];
