<?php
/**
 * YikaiCMS - Spanish language pack (es).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'pcar_block_name' => 'Carrusel de productos',
    'pcar_f_title' => 'Título',
    'pcar_title_ph' => 'Por ejemplo: productos destacados',
    'pcar_per_screen' => 'Elementos por pantalla',
    'pcar_autoplay' => 'Reproducción automática',
    'pcar_on' => 'Activada',
    'pcar_interval' => 'Intervalo (segundos)',
    'pcar_selected' => 'Productos seleccionados (orden de presentación; utilice las flechas para subir o bajar)',
    'pcar_item_fallback' => 'Producto #',
    'pcar_none_selected' => 'Todavía no hay productos seleccionados',
    'pcar_batch_add' => 'Añadir por lotes',
    'pcar_search_ph' => 'Filtrar por nombre de producto…',
    'pcar_no_published' => 'Todavía no hay productos publicados',
    'pcar_add_checked' => 'Añadir los productos marcados',
    'pcar_prev_group' => 'Grupo anterior',
    'pcar_next_group' => 'Grupo siguiente',
];
