<?php
/**
 * YikaiCMS - French language pack (fr).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'pcar_block_name' => 'Carrousel de produits',
    'pcar_f_title' => 'Titre',
    'pcar_title_ph' => 'Par exemple : Produits mis en avant',
    'pcar_per_screen' => 'Éléments par vue',
    'pcar_autoplay' => 'Lecture automatique',
    'pcar_on' => 'Activée',
    'pcar_interval' => 'Intervalle (secondes)',
    'pcar_selected' => 'Produits sélectionnés (ordre d’affichage ; utilisez les flèches pour les réorganiser)',
    'pcar_item_fallback' => 'Produit n°',
    'pcar_none_selected' => 'Aucun produit sélectionné pour le moment',
    'pcar_batch_add' => 'Ajouter en série',
    'pcar_search_ph' => 'Filtrer par nom de produit…',
    'pcar_no_published' => 'Aucun produit publié',
    'pcar_add_checked' => 'Ajouter la sélection',
    'pcar_prev_group' => 'Précédent',
    'pcar_next_group' => 'Suivant',
];
