<?php
/**
 * YikaiCMS - Indonesian language pack (id).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'pcar_block_name' => 'Carousel produk',
    'pcar_f_title' => 'Judul',
    'pcar_title_ph' => 'Mis.: Produk unggulan',
    'pcar_per_screen' => 'Item per tampilan',
    'pcar_autoplay' => 'Putar otomatis',
    'pcar_on' => 'Aktif',
    'pcar_interval' => 'Interval (detik)',
    'pcar_selected' => 'Produk terpilih (urutan tampil; gunakan panah untuk memindahkan)',
    'pcar_item_fallback' => 'Produk #',
    'pcar_none_selected' => 'Belum ada produk yang dipilih',
    'pcar_batch_add' => 'Tambah massal',
    'pcar_search_ph' => 'Filter berdasarkan nama produk…',
    'pcar_no_published' => 'Belum ada produk yang diterbitkan',
    'pcar_add_checked' => 'Tambah produk yang dicentang',
    'pcar_prev_group' => 'Sebelumnya',
    'pcar_next_group' => 'Berikutnya',
];
