<?php
/**
 * YikaiCMS - Italian language pack (it).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'pcar_block_name' => 'Carosello prodotti',
    'pcar_f_title' => 'Titolo',
    'pcar_title_ph' => 'es. Prodotti in evidenza',
    'pcar_per_screen' => 'Elementi per vista',
    'pcar_autoplay' => 'Riproduzione automatica',
    'pcar_on' => 'Attivo',
    'pcar_interval' => 'Intervallo (secondi)',
    'pcar_selected' => 'Prodotti selezionati (l\'ordine è quello di visualizzazione; usa le frecce per riordinare)',
    'pcar_item_fallback' => 'Prodotto #',
    'pcar_none_selected' => 'Nessun prodotto selezionato',
    'pcar_batch_add' => 'Aggiungi in blocco',
    'pcar_search_ph' => 'Filtra per nome prodotto…',
    'pcar_no_published' => 'Nessun prodotto pubblicato',
    'pcar_add_checked' => 'Aggiungi selezionati',
    'pcar_prev_group' => 'Precedente',
    'pcar_next_group' => 'Successivo',
];
