<?php
/**
 * YikaiCMS - Korean language pack (ko).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'pcar_block_name' => '제품 슬라이더',
    'pcar_f_title' => '제목',
    'pcar_title_ph' => '예: 추천 제품',
    'pcar_per_screen' => '화면당 개수',
    'pcar_autoplay' => '자동 재생',
    'pcar_on' => '사용',
    'pcar_interval' => '간격(초)',
    'pcar_selected' => '선택된 제품(순서가 표시 순서이며, 위/아래로 이동 가능)',
    'pcar_item_fallback' => '제품 #',
    'pcar_none_selected' => '아직 선택된 제품이 없습니다',
    'pcar_batch_add' => '일괄 추가',
    'pcar_search_ph' => '제품명으로 필터링…',
    'pcar_no_published' => '발행된 제품이 없습니다',
    'pcar_add_checked' => '선택한 제품 추가',
    'pcar_prev_group' => '이전 그룹',
    'pcar_next_group' => '다음 그룹',
];
