<?php
/**
 * YikaiCMS - Malay language pack (ms).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'pcar_block_name' => 'Karusel produk',
    'pcar_f_title' => 'Tajuk',
    'pcar_title_ph' => 'cth. Produk ditampilkan',
    'pcar_per_screen' => 'Item setiap paparan',
    'pcar_autoplay' => 'Main automatik',
    'pcar_on' => 'Hidup',
    'pcar_interval' => 'Selang (saat)',
    'pcar_selected' => 'Produk dipilih (urutan paparan; gunakan anak panah untuk menyusun semula)',
    'pcar_item_fallback' => 'Produk #',
    'pcar_none_selected' => 'Belum ada produk dipilih',
    'pcar_batch_add' => 'Tambah secara pukal',
    'pcar_search_ph' => 'Tapis mengikut nama produk…',
    'pcar_no_published' => 'Tiada produk diterbitkan',
    'pcar_add_checked' => 'Tambah pilihan',
    'pcar_prev_group' => 'Sebelumnya',
    'pcar_next_group' => 'Seterusnya',
];
