<?php
/**
 * YikaiCMS - Brazilian Portuguese language pack (pt).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'pcar_block_name' => 'Carrossel de produtos',
    'pcar_f_title' => 'Título',
    'pcar_title_ph' => 'Por exemplo: Produtos em destaque',
    'pcar_per_screen' => 'Itens por tela',
    'pcar_autoplay' => 'Reprodução automática',
    'pcar_on' => 'Ativada',
    'pcar_interval' => 'Intervalo (segundos)',
    'pcar_selected' => 'Produtos selecionados (ordem de exibição; use as setas para mover para cima ou para baixo)',
    'pcar_item_fallback' => 'Produto #',
    'pcar_none_selected' => 'Nenhum produto selecionado ainda',
    'pcar_batch_add' => 'Adicionar em lote',
    'pcar_search_ph' => 'Filtrar pelo nome do produto…',
    'pcar_no_published' => 'Nenhum produto publicado',
    'pcar_add_checked' => 'Adicionar produtos selecionados',
    'pcar_prev_group' => 'Grupo anterior',
    'pcar_next_group' => 'Próximo grupo',
];
