<?php
/**
 * YikaiCMS - Thai language pack (th).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'pcar_block_name' => 'สไลด์สินค้า',
    'pcar_f_title' => 'หัวข้อ',
    'pcar_title_ph' => 'เช่น: สินค้าแนะนำ',
    'pcar_per_screen' => 'จำนวนต่อหน้าจอ',
    'pcar_autoplay' => 'เล่นอัตโนมัติ',
    'pcar_on' => 'เปิด',
    'pcar_interval' => 'ช่วงเวลา (วินาที)',
    'pcar_selected' => 'สินค้าที่เลือก (ลำดับคือลำดับการแสดง เลื่อนขึ้นลงได้)',
    'pcar_item_fallback' => 'สินค้า #',
    'pcar_none_selected' => 'ยังไม่ได้เลือกสินค้า',
    'pcar_batch_add' => 'เพิ่มแบบกลุ่ม',
    'pcar_search_ph' => 'กรองตามชื่อสินค้า…',
    'pcar_no_published' => 'ไม่มีสินค้าที่เผยแพร่แล้ว',
    'pcar_add_checked' => 'เพิ่มสินค้าที่เลือก',
    'pcar_prev_group' => 'ก่อนหน้า',
    'pcar_next_group' => 'ถัดไป',
];
