<?php
/**
 * YikaiCMS - Turkish language pack (tr).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'pcar_block_name' => 'Ürün karuseli',
    'pcar_f_title' => 'Başlık',
    'pcar_title_ph' => 'örn. Öne çıkan ürünler',
    'pcar_per_screen' => 'Görünüm başına öğe',
    'pcar_autoplay' => 'Otomatik oynat',
    'pcar_on' => 'Açık',
    'pcar_interval' => 'Aralık (saniye)',
    'pcar_selected' => 'Seçili ürünler (görüntüleme sırası; sıralamak için okları kullanın)',
    'pcar_item_fallback' => 'Ürün #',
    'pcar_none_selected' => 'Henüz ürün seçilmedi',
    'pcar_batch_add' => 'Toplu ekle',
    'pcar_search_ph' => 'Ürün adına göre filtrele…',
    'pcar_no_published' => 'Yayınlanmış ürün yok',
    'pcar_add_checked' => 'Seçilenleri ekle',
    'pcar_prev_group' => 'Önceki',
    'pcar_next_group' => 'Sonraki',
];
