<?php
/**
 * YikaiCMS - Vietnamese language pack (vi).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'pcar_block_name' => 'Băng chuyền sản phẩm',
    'pcar_f_title' => 'Tiêu đề',
    'pcar_title_ph' => 'Ví dụ: sản phẩm nổi bật',
    'pcar_per_screen' => 'Số mục mỗi màn hình',
    'pcar_autoplay' => 'Tự động phát',
    'pcar_on' => 'Bật',
    'pcar_interval' => 'Khoảng thời gian (giây)',
    'pcar_selected' => 'Sản phẩm đã chọn (thứ tự là thứ tự hiển thị, có thể di chuyển lên xuống)',
    'pcar_item_fallback' => 'Sản phẩm #',
    'pcar_none_selected' => 'Chưa chọn sản phẩm',
    'pcar_batch_add' => 'Thêm hàng loạt',
    'pcar_search_ph' => 'Tìm theo tên sản phẩm…',
    'pcar_no_published' => 'Chưa có sản phẩm đã xuất bản',
    'pcar_add_checked' => 'Thêm sản phẩm đã chọn',
    'pcar_prev_group' => 'Trước',
    'pcar_next_group' => 'Tiếp',
];
