<?php
/**
 * YikaiCMS - Traditional Chinese (Taiwan) language pack (zh-TW).
 * Generated by tools/i18n/zh-tw.php from zh-CN via OpenCC; reviewed wording is kept while the zh-CN source is unchanged.
 * Content is not here: it stays in Simplified Chinese and the front end converts each page.
 */

return [
    'pcar_block_name' => '產品輪播',
    'pcar_f_title' => '標題',
    'pcar_title_ph' => '如：精選產品',
    'pcar_per_screen' => '每屏個數',
    'pcar_autoplay' => '自動播放',
    'pcar_on' => '開啟',
    'pcar_interval' => '間隔（秒）',
    'pcar_selected' => '已選產品（順序即展示順序，可上下移）',
    'pcar_item_fallback' => '產品 #',
    'pcar_none_selected' => '尚未選擇產品',
    'pcar_batch_add' => '批次新增',
    'pcar_search_ph' => '搜尋產品名篩選…',
    'pcar_no_published' => '暫無已發佈產品',
    'pcar_add_checked' => '新增勾選的產品',
    'pcar_prev_group' => '上一組',
    'pcar_next_group' => '下一組',
];
