<?php
/**
 * YikaiCMS - Spanish language pack (es).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'ann_admin_title' => 'Ventana de anuncios del sitio',
    'ann_admin_desc' => 'Al activarla, los visitantes verán un anuncio al entrar en el sitio, como una declaración oficial o un aviso de cierre por vacaciones. Se muestra una vez por visitante durante el intervalo de días configurado. :b Si modifica el título o el contenido, volverá a mostrarse una vez a todos los visitantes :_b.',
    'ann_enable' => 'Activar la ventana de anuncios',
    'ann_f_title' => 'Título de la ventana',
    'ann_f_content' => 'Contenido del anuncio',
    'ann_content_tip' => 'Edición visual con negrita, texto centrado, imágenes y más. El título y el botón se configuran por separado abajo.',
    'ann_f_button' => 'Texto del botón',
    'ann_button_tip' => 'Por ejemplo: «Entendido», «Aceptar y continuar» o «Cerrar»',
    'ann_f_freq' => 'Frecuencia de aparición',
    'ann_freq_unit' => 'días entre apariciones (0 = mostrar siempre)',
    'ann_home_only' => 'Solo en la página de inicio (sin marcar = en todas las páginas)',
    'ann_save' => 'Guardar',
    'ann_test_tip' => 'Si no ve la ventana durante las pruebas, la cookie del intervalo (:code) está activa. Utilice una ventana privada, elimine la cookie o configure temporalmente la frecuencia en 0.',
    'ann_tip_label' => 'Consejo:',
    'ann_editor_ph' => 'Texto del anuncio…',
    'ann_log_update' => 'Se ha actualizado la configuración de anuncios del sitio',
    'ann_default_title' => 'Anuncio del sitio',
    'ann_default_btn' => 'Entendido',
    'ann_close' => 'Cerrar',
];
