<?php
/**
 * YikaiCMS - French language pack (fr).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'ann_admin_title' => 'Fenêtre d’annonce',
    'ann_admin_desc' => 'Lorsqu’elle est activée, une fenêtre s’affiche à l’arrivée des visiteurs — pratique pour annoncer une fermeture pendant les fêtes ou une déclaration officielle. Chaque visiteur la voit une fois pendant la période de suspension définie. :b Si vous modifiez le titre ou le texte, elle s’affiche à nouveau pour tout le monde.:_b',
    'ann_enable' => 'Activer la fenêtre',
    'ann_f_title' => 'Titre de la fenêtre',
    'ann_f_content' => 'Texte de l’annonce',
    'ann_content_tip' => 'Édition visuelle avec gras, centrage, images, etc. Le titre et le bouton se définissent séparément ci-dessous.',
    'ann_f_button' => 'Libellé du bouton',
    'ann_button_tip' => 'Par exemple : Compris, Accepter et continuer ou Fermer.',
    'ann_f_freq' => 'Fréquence d’affichage',
    'ann_freq_unit' => 'jours entre deux affichages (0 = affichage à chaque visite)',
    'ann_home_only' => 'Page d’accueil uniquement (décocher pour afficher sur toutes les pages)',
    'ann_save' => 'Enregistrer',
    'ann_test_tip' => 'Si la fenêtre ne s’affiche pas pendant votre test, le cookie de suspension (:code) fonctionne. Utilisez une fenêtre privée, effacez le cookie ou réglez temporairement la fréquence sur 0.',
    'ann_tip_label' => 'Conseil :',
    'ann_editor_ph' => 'Texte de l’annonce…',
    'ann_log_update' => 'Paramètres de l’annonce mis à jour',
    'ann_default_title' => 'Annonce',
    'ann_default_btn' => 'Compris',
    'ann_close' => 'Fermer',
];
