<?php
/**
 * YikaiCMS - Indonesian language pack (id).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'ann_admin_title' => 'Popup pengumuman situs',
    'ann_admin_desc' => 'Jika diaktifkan, pengunjung akan melihat popup saat memasuki situs (misalnya pernyataan resmi atau pemberitahuan libur). Pengunjung yang sama hanya melihatnya sekali dalam periode jeda yang ditentukan. :b Jika Anda mengubah judul atau isinya, popup akan muncul lagi untuk semua pengunjung. :_b',
    'ann_enable' => 'Aktifkan popup pengumuman',
    'ann_f_title' => 'Judul popup',
    'ann_f_content' => 'Isi pengumuman',
    'ann_content_tip' => 'Edit visual, mendukung tebal, rata tengah, sisip gambar, dan lain-lain; judul dan tombol diatur terpisah di bawah.',
    'ann_f_button' => 'Teks tombol',
    'ann_button_tip' => 'Misalnya "Mengerti", "Setuju dan lanjutkan", "Tutup", dan lain-lain',
    'ann_f_freq' => 'Frekuensi tampil',
    'ann_freq_unit' => 'hari sekali (0 = tampil setiap kali)',
    'ann_home_only' => 'Hanya di beranda (tidak dicentang = setiap halaman seluruh situs)',
    'ann_save' => 'Simpan',
    'ann_test_tip' => 'Jika Anda tidak melihat popup saat menguji, itu karena cookie "jeda" (:code) sedang berlaku—gunakan jendela privat, hapus cookie, atau setel frekuensi tampil ke 0 untuk sementara.',
    'ann_tip_label' => 'Tips:',
    'ann_editor_ph' => 'Isi pengumuman…',
    'ann_log_update' => 'Memperbarui pengaturan pengumuman situs',
    'ann_default_title' => 'Pengumuman situs',
    'ann_default_btn' => 'Mengerti',
    'ann_close' => 'Tutup',
];
