<?php
/**
 * YikaiCMS - Italian language pack (it).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'ann_admin_title' => 'Popup annuncio',
    'ann_admin_desc' => 'Se attivato, i visitatori vedono un popup all\'arrivo — utile per avvisi come chiusure festive o comunicazioni ufficiali. Ogni visitatore lo vede una volta entro il periodo di raffreddamento impostato. :b Se modifichi il titolo o il testo, viene mostrato di nuovo a tutti.:_b',
    'ann_enable' => 'Attiva il popup',
    'ann_f_title' => 'Titolo del popup',
    'ann_f_content' => 'Testo dell\'annuncio',
    'ann_content_tip' => 'Modifica visuale con grassetto, centratura, immagini e altro. Titolo e pulsante si impostano separatamente qui sotto.',
    'ann_f_button' => 'Etichetta del pulsante',
    'ann_button_tip' => 'Ad esempio: Ho capito, Accetto e continuo, oppure Chiudi.',
    'ann_f_freq' => 'Frequenza di visualizzazione',
    'ann_freq_unit' => 'giorni tra una visualizzazione e l\'altra (0 = ogni volta)',
    'ann_home_only' => 'Solo home page (non selezionato = tutte le pagine)',
    'ann_save' => 'Salva',
    'ann_test_tip' => 'Se durante il test non vedi il popup, il cookie di raffreddamento (:code) sta funzionando. Usa una finestra anonima, cancella il cookie oppure imposta temporaneamente la frequenza a 0.',
    'ann_tip_label' => 'Suggerimento:',
    'ann_editor_ph' => 'Testo dell\'annuncio…',
    'ann_log_update' => 'Impostazioni annuncio aggiornate',
    'ann_default_title' => 'Annuncio',
    'ann_default_btn' => 'Ho capito',
    'ann_close' => 'Chiudi',
];
