<?php
/**
 * YikaiCMS - Korean language pack (ko).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'ann_admin_title' => '사이트 공지 팝업',
    'ann_admin_desc' => '활성화하면 방문자가 사이트에 접속할 때 공지 팝업이 표시됩니다(예: 엄정 성명, 휴무 안내). 동일 방문자에게는 설정한 쿨다운 일수 내에 한 번만 표시됩니다. :b제목이나 내용을 수정하면 모든 방문자에게 자동으로 다시 한 번 표시됩니다:_b.',
    'ann_enable' => '공지 팝업 사용',
    'ann_f_title' => '팝업 제목',
    'ann_f_content' => '공지 내용',
    'ann_content_tip' => '시각적 편집을 지원합니다(굵게, 가운데 정렬, 이미지 삽입 등). 제목과 버튼은 아래에서 별도로 설정합니다.',
    'ann_f_button' => '버튼 문구',
    'ann_button_tip' => '예: “알겠습니다” “동의하고 계속” “닫기” 등',
    'ann_f_freq' => '표시 빈도',
    'ann_freq_unit' => '며칠에 한 번(0 = 매번 표시)',
    'ann_home_only' => '홈페이지만 표시(미체크 시 모든 페이지)',
    'ann_save' => '저장',
    'ann_test_tip' => '테스트 중 자신에게 팝업이 보이지 않는다면 “쿨다운” cookie(:code)가 작동 중인 것입니다. 시크릿 창을 사용하거나 cookie를 삭제하거나, 표시 빈도를 잠시 0으로 설정하면 됩니다.',
    'ann_tip_label' => '안내:',
    'ann_editor_ph' => '공지 본문…',
    'ann_log_update' => '사이트 공지 설정을 업데이트했습니다',
    'ann_default_title' => '사이트 공지',
    'ann_default_btn' => '알겠습니다',
    'ann_close' => '닫기',
];
