<?php
/**
 * YikaiCMS - Malay language pack (ms).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'ann_admin_title' => 'Tetingkap timbul pengumuman laman',
    'ann_admin_desc' => 'Apabila dihidupkan, pelawat melihat tetingkap timbul semasa tiba — berguna untuk notis seperti cuti atau kenyataan rasmi. Setiap pelawat melihatnya sekali dalam tempoh penyejukan yang anda tetapkan. :b Jika anda menukar tajuk atau isi kandungan, ia akan muncul semula kepada semua orang.:_b',
    'ann_enable' => 'Dayakan tetingkap timbul',
    'ann_f_title' => 'Tajuk tetingkap timbul',
    'ann_f_content' => 'Isi kandungan pengumuman',
    'ann_content_tip' => 'Penyuntingan visual dengan tebal, pemusatan, imej dan sebagainya. Tajuk dan butang ditetapkan secara berasingan di bawah.',
    'ann_f_button' => 'Label butang',
    'ann_button_tip' => 'Contohnya: Faham, Setuju dan teruskan, atau Tutup.',
    'ann_f_freq' => 'Kekerapan paparan',
    'ann_freq_unit' => 'hari antara paparan (0 memaparkan setiap kali)',
    'ann_home_only' => 'Halaman utama sahaja (tidak ditanda memaparkan pada setiap halaman)',
    'ann_save' => 'Simpan',
    'ann_test_tip' => 'Jika anda tidak dapat melihat tetingkap timbul semasa menguji, cookie penyejukan (:code) sedang berfungsi. Gunakan tetingkap peribadi, kosongkan cookie, atau tetapkan kekerapan kepada 0 buat seketika.',
    'ann_tip_label' => 'Petua:',
    'ann_editor_ph' => 'Teks pengumuman…',
    'ann_log_update' => 'Tetapan pengumuman dikemas kini',
    'ann_default_title' => 'Pengumuman',
    'ann_default_btn' => 'Faham',
    'ann_close' => 'Tutup',
];
