<?php
/**
 * YikaiCMS - Brazilian Portuguese language pack (pt).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'ann_admin_title' => 'Pop-up de avisos do site',
    'ann_admin_desc' => 'Quando ativado, os visitantes veem um aviso ao entrar no site, como comunicado oficial ou aviso de recesso. Cada visitante vê o pop-up apenas uma vez durante o intervalo de dias definido. :b Ao alterar o título ou o conteúdo, o pop-up será exibido novamente a todos os visitantes.:_b',
    'ann_enable' => 'Ativar pop-up de avisos',
    'ann_f_title' => 'Título do pop-up',
    'ann_f_content' => 'Conteúdo do aviso',
    'ann_content_tip' => 'Edição visual com negrito, alinhamento central, imagens e outros recursos. O título e o botão são configurados separadamente abaixo.',
    'ann_f_button' => 'Texto do botão',
    'ann_button_tip' => 'Por exemplo: “Entendi”, “Concordar e continuar” ou “Fechar”',
    'ann_f_freq' => 'Frequência de exibição',
    'ann_freq_unit' => 'dias entre exibições (0 = exibir sempre)',
    'ann_home_only' => 'Exibir apenas na página inicial (desmarcado = todas as páginas)',
    'ann_save' => 'Salvar',
    'ann_test_tip' => 'Se o pop-up não aparecer para você durante o teste, o cookie de intervalo (:code) está em vigor. Use uma janela anônima, limpe o cookie ou defina temporariamente a frequência como 0.',
    'ann_tip_label' => 'Dica:',
    'ann_editor_ph' => 'Texto do aviso…',
    'ann_log_update' => 'Configurações de avisos do site atualizadas',
    'ann_default_title' => 'Aviso do site',
    'ann_default_btn' => 'Entendi',
    'ann_close' => 'Fechar',
];
