<?php
/**
 * YikaiCMS - Turkish language pack (tr).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'ann_admin_title' => 'Site duyuru açılır penceresi',
    'ann_admin_desc' => 'Etkinleştirildiğinde ziyaretçiler siteye geldiğinde bir duyuru görür (tatil kapanışları veya resmî açıklamalar gibi). Her ziyaretçi belirlediğiniz bekleme süresi içinde bir kez görür. :b Başlığı veya metni değiştirirseniz herkese yeniden gösterilir.:_b',
    'ann_enable' => 'Açılır pencereyi etkinleştir',
    'ann_f_title' => 'Açılır pencere başlığı',
    'ann_f_content' => 'Duyuru metni',
    'ann_content_tip' => 'Görsel düzenleme; kalın, ortala, görsel ekleme vb. desteklenir. Başlık ve düğme aşağıda ayrıca ayarlanır.',
    'ann_f_button' => 'Düğme etiketi',
    'ann_button_tip' => 'Örneğin: Anladım, Kabul et ve devam et veya Kapat.',
    'ann_f_freq' => 'Gösterim sıklığı',
    'ann_freq_unit' => 'gösterimler arası gün (0 her seferinde gösterir)',
    'ann_home_only' => 'Yalnızca ana sayfa (işaretlenmezse her sayfada gösterilir)',
    'ann_save' => 'Kaydet',
    'ann_test_tip' => 'Test sırasında açılır pencereyi göremiyorsanız bekleme cookie\'si (:code) görevini yapıyor. Gizli pencere kullanın, cookie\'yi temizleyin veya sıklığı geçici olarak 0 yapın.',
    'ann_tip_label' => 'İpucu:',
    'ann_editor_ph' => 'Duyuru metni…',
    'ann_log_update' => 'Duyuru ayarları güncellendi',
    'ann_default_title' => 'Duyuru',
    'ann_default_btn' => 'Anladım',
    'ann_close' => 'Kapat',
];
