<?php
/**
 * YikaiCMS - Vietnamese language pack (vi).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'ann_admin_title' => 'Popup thông báo trang web',
    'ann_admin_desc' => 'Khi bật, khách truy cập sẽ thấy thông báo bật lên khi vào trang web (ví dụ: tuyên bố chính thức, thông báo nghỉ lễ). Mỗi khách chỉ thấy một lần trong số ngày chờ bạn đặt; :b sau khi bạn sửa tiêu đề hoặc nội dung, thông báo sẽ tự động bật lại một lần cho tất cả khách :_b.',
    'ann_enable' => 'Bật popup thông báo',
    'ann_f_title' => 'Tiêu đề popup',
    'ann_f_content' => 'Nội dung thông báo',
    'ann_content_tip' => 'Chỉnh sửa trực quan, hỗ trợ in đậm, căn giữa, chèn hình ảnh, v.v.; tiêu đề và nút được đặt riêng ở bên dưới.',
    'ann_f_button' => 'Chữ trên nút',
    'ann_button_tip' => 'Ví dụ: “Tôi đã hiểu”, “Đồng ý và tiếp tục”, “Đóng”, v.v.',
    'ann_f_freq' => 'Tần suất hiển thị',
    'ann_freq_unit' => 'ngày một lần (0 = hiển thị mỗi lần)',
    'ann_home_only' => 'Chỉ hiển thị ở trang chủ (không tích = mọi trang trong site)',
    'ann_save' => 'Lưu',
    'ann_test_tip' => 'Khi kiểm thử nếu bạn không thấy popup, đó là do cookie “chờ” (:code) đang hoạt động — hãy dùng cửa sổ ẩn danh hoặc xóa cookie, hoặc tạm đặt tần suất hiển thị về 0.',
    'ann_tip_label' => 'Gợi ý:',
    'ann_editor_ph' => 'Nội dung thông báo…',
    'ann_log_update' => 'Đã cập nhật cấu hình thông báo trang web',
    'ann_default_title' => 'Thông báo trang web',
    'ann_default_btn' => 'Tôi đã hiểu',
    'ann_close' => 'Đóng',
];
