<?php
/**
 * YikaiCMS - Traditional Chinese (Taiwan) language pack (zh-TW).
 * Generated by tools/i18n/zh-tw.php from zh-CN via OpenCC; reviewed wording is kept while the zh-CN source is unchanged.
 * Content is not here: it stays in Simplified Chinese and the front end converts each page.
 */

return [
    'ann_admin_title' => '網站公告彈窗',
    'ann_admin_desc' => '開啟後，訪客進入網站時會彈出公告（如嚴正宣告、放假通知）。同一訪客在設定的冷卻天數內只彈一次；:b你修改標題或內容後，會自動對所有訪客重新彈出一次:_b。',
    'ann_enable' => '啟用公告彈窗',
    'ann_f_title' => '彈窗標題',
    'ann_f_content' => '公告內容',
    'ann_content_tip' => '視覺化編輯，支援加粗、居中、插入圖片等；標題與按鈕由下方單獨設定。',
    'ann_f_button' => '按鈕文字',
    'ann_button_tip' => '如「我知道了」「同意並繼續」「關閉」等',
    'ann_f_freq' => '彈出頻率',
    'ann_freq_unit' => '天一次（0＝每次都彈）',
    'ann_home_only' => '僅首頁顯示（不勾選＝全站每頁）',
    'ann_save' => '儲存',
    'ann_test_tip' => '測試時如果自己看不到彈窗，是「冷卻」cookie（:code）生效了——用無痕視窗或清 cookie，或臨時把彈出頻率設為 0 即可。',
    'ann_tip_label' => '提示：',
    'ann_editor_ph' => '公告正文……',
    'ann_log_update' => '更新網站公告配置',
    'ann_default_title' => '網站公告',
    'ann_default_btn' => '我知道了',
    'ann_close' => '關閉',
];
