<?php
/**
 * YikaiCMS - Arabic language pack (ar).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'cc_title' => 'شريط الموافقة على ملفات تعريف الارتباط',
    'cc_desc' => 'جاهز للامتثال لـ GDPR / PIPL: ثلاث فئات للموافقة (ضرورية / تحليلية / تسويقية) مع مدخل دائم للسحب. يمكن للنصوص الأخرى التحكم في تحميلها حسب الفئة عبر :api1 أو حدث :api2 (على جانب PHP عبر :api3).',
    'cc_policy_url' => 'رابط سياسة الخصوصية',
    'cc_policy_tip' => 'عند التعيين، يعرض الشريط رابطًا إلى سياسة الخصوصية. يتطلب GDPR ذلك فعليًا.',
    'cc_policy_ver' => 'إصدار السياسة',
    'cc_policy_ver_tip' => 'زد هذا الرقم :b+1:_b كلما تغيّر استخدامك لملفات تعريف الارتباط أو سياسة الخصوصية تغييرًا جوهريًا. تُلغى جميع الموافقات الحالية ويطلب الشريط الموافقة مجددًا.',
    'cc_consent_mode' => 'تفعيل Google Consent Mode v2',
    'cc_consent_mode_tip' => 'يصدر إشارات consent default/update إلى gtag (analytics_storage / ad_storage / ad_user_data / ad_personalization).',
    'cc_footer_link' => 'عرض مدخل دائم «إعدادات ملفات تعريف الارتباط» (أسفل اليسار)',
    'cc_footer_link_tip' => 'يسمح للزوار بسحب الموافقة أو تغييرها في أي وقت. تتطلب المادة 7(3) من GDPR أن يكون سحب الموافقة بسهولة منحها، لذا أبقِ هذا الخيار مفعّلًا.',
    'cc_save' => 'حفظ',
    'cc_example_title' => 'مثال على الدمج: تحميل GA بعد الموافقة فقط',
    'cc_example_note' => 'مع تفعيل Consent Mode v2 يمكنك أيضًا تحميل gtag.js دون شرط، فتُخفّض Google الإعدادات إلى طلبات ping بدون ملفات تعريف ارتباط بناءً على إشارات الموافقة.',
    'cc_log_update' => 'تم تحديث إعدادات الموافقة على ملفات تعريف الارتباط',
];
