<?php
/**
 * YikaiCMS - Spanish language pack (es).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'cc_title' => 'Aviso de consentimiento de cookies',
    'cc_desc' => 'Conformidad con GDPR / PIPL: tres categorías de consentimiento (necesarias / análisis / marketing) y un acceso para retirarlo en cualquier momento. Otros scripts pueden controlar su carga por categoría mediante :api1 o el evento :api2 (:api3 en PHP).',
    'cc_policy_url' => 'Enlace a la política de privacidad',
    'cc_policy_tip' => 'Al introducirlo, el aviso mostrará el enlace «Política de privacidad». Se recomienda incluirlo para cumplir el GDPR.',
    'cc_policy_ver' => 'Versión de la política',
    'cc_policy_ver_tip' => 'Cuando cambie sustancialmente el uso de cookies o la política de privacidad, incremente la versión :b+1:_b. Los consentimientos anteriores dejarán de ser válidos y el aviso volverá a solicitar el consentimiento.',
    'cc_consent_mode' => 'Activar Google Consent Mode v2',
    'cc_consent_mode_tip' => 'Envía señales consent default/update a gtag (analytics_storage / ad_storage / ad_user_data / ad_personalization).',
    'cc_footer_link' => 'Mostrar un acceso permanente a «Configuración de cookies» (abajo a la izquierda)',
    'cc_footer_link_tip' => 'Permite retirar o cambiar el consentimiento en cualquier momento. El artículo 7(3) del GDPR exige que retirarlo sea tan fácil como darlo; se recomienda mantener esta opción activada.',
    'cc_save' => 'Guardar',
    'cc_example_title' => 'Ejemplo de integración: cargar GA tras el consentimiento',
    'cc_example_note' => 'Si activa Consent Mode v2, también puede cargar gtag.js siempre. Google adapta su funcionamiento a las señales consent y envía pings sin cookies.',
    'cc_log_update' => 'Se ha actualizado la configuración de consentimiento de cookies',
];
