<?php
/**
 * YikaiCMS - French language pack (fr).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'cc_title' => 'Bandeau de consentement aux cookies',
    'cc_desc' => 'Compatible avec le RGPD et la PIPL : trois catégories de consentement (nécessaire, analytique, marketing) et une entrée permanente pour retirer son consentement. Les autres scripts peuvent se conditionner par catégorie avec :api1 ou l’événement :api2 (:api3 côté PHP).',
    'cc_policy_url' => 'Lien vers la politique de confidentialité',
    'cc_policy_tip' => 'Si ce lien est renseigné, le bandeau affiche votre politique de confidentialité. Le RGPD l’exige dans les faits.',
    'cc_policy_ver' => 'Version de la politique',
    'cc_policy_ver_tip' => 'Augmentez cette valeur de :b+1:_b à chaque modification importante de l’usage des cookies ou de la politique de confidentialité. Tous les consentements existants sont invalidés et une nouvelle demande s’affiche.',
    'cc_consent_mode' => 'Activer Google Consent Mode v2',
    'cc_consent_mode_tip' => 'Émet les signaux par défaut et de mise à jour du consentement pour gtag (analytics_storage / ad_storage / ad_user_data / ad_personalization).',
    'cc_footer_link' => 'Afficher en permanence « Paramètres des cookies » (en bas à gauche)',
    'cc_footer_link_tip' => 'Permet aux visiteurs de retirer ou modifier leur consentement à tout moment. Selon l’article 7(3) du RGPD, le retrait du consentement doit être aussi facile que son accord ; laissez cette option activée.',
    'cc_save' => 'Enregistrer',
    'cc_example_title' => 'Exemple : charger GA uniquement après consentement',
    'cc_example_note' => 'Avec Consent Mode v2 activé, vous pouvez aussi charger gtag.js systématiquement ; Google utilise alors des signaux sans cookies en fonction des choix de consentement.',
    'cc_log_update' => 'Paramètres de consentement aux cookies mis à jour',
];
