<?php
/**
 * YikaiCMS - Indonesian language pack (id).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'cc_title' => 'Spanduk persetujuan Cookie',
    'cc_desc' => 'Sesuai GDPR / PIPL: tiga kategori persetujuan (wajib/analitik/pemasaran) + pintu penarikan kapan saja. Skrip lain dapat dikontrol per kategori melalui :api1 atau peristiwa :api2 (di sisi PHP gunakan :api3).',
    'cc_policy_url' => 'Tautan kebijakan privasi',
    'cc_policy_tip' => 'Jika diisi, teks spanduk menampilkan tautan "Kebijakan privasi" (disarankan oleh GDPR).',
    'cc_policy_ver' => 'Versi kebijakan',
    'cc_policy_ver_tip' => 'Naikkan :b+1:_b setiap kali cara penggunaan cookie atau kebijakan privasi berubah secara material: semua persetujuan lama menjadi tidak berlaku dan spanduk muncul lagi untuk meminta persetujuan.',
    'cc_consent_mode' => 'Aktifkan Google Consent Mode v2',
    'cc_consent_mode_tip' => 'Mengirim sinyal consent default/update ke gtag (analytics_storage / ad_storage / ad_user_data / ad_personalization).',
    'cc_footer_link' => 'Tampilkan pintu "Pengaturan Cookie" yang selalu ada (kiri bawah)',
    'cc_footer_link_tip' => 'Memungkinkan pengunjung menarik atau mengubah persetujuan kapan saja—Pasal 7(3) GDPR mengharuskan penarikan persetujuan semudah memberikannya, jadi sebaiknya tetap aktif.',
    'cc_save' => 'Simpan',
    'cc_example_title' => 'Contoh integrasi: muat GA sesuai persetujuan',
    'cc_example_note' => 'Jika Consent Mode v2 diaktifkan, Anda juga dapat memuat gtag.js secara permanen—Google akan menurunkan sendiri ke ping tanpa Cookie sesuai sinyal consent.',
    'cc_log_update' => 'Memperbarui pengaturan persetujuan Cookie',
];
