<?php
/**
 * YikaiCMS - Italian language pack (it).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'cc_title' => 'Banner consenso cookie',
    'cc_desc' => 'Conforme a GDPR / PIPL: tre categorie di consenso (necessari, analisi, marketing) più un accesso per revocare in qualsiasi momento. Altri script possono caricarsi per categoria tramite :api1 o l\'evento :api2 (:api3 lato PHP).',
    'cc_policy_url' => 'Link all\'informativa sulla privacy',
    'cc_policy_tip' => 'Se impostato, il banner mostra un link alla tua informativa sulla privacy. Il GDPR lo richiede di fatto.',
    'cc_policy_ver' => 'Versione dell\'informativa',
    'cc_policy_ver_tip' => 'Aumenta questo valore di :b+1:_b ogni volta che l\'uso dei cookie o l\'informativa sulla privacy cambia in modo sostanziale. Tutti i consensi esistenti vengono invalidati e il banner li richiede di nuovo.',
    'cc_consent_mode' => 'Attiva Google Consent Mode v2',
    'cc_consent_mode_tip' => 'Invia a gtag i segnali consent default/update (analytics_storage / ad_storage / ad_user_data / ad_personalization).',
    'cc_footer_link' => 'Mostra una voce fissa «Impostazioni cookie» (in basso a sinistra)',
    'cc_footer_link_tip' => 'Consente ai visitatori di revocare o modificare il consenso in qualsiasi momento. L\'art. 7(3) del GDPR richiede che revocare sia facile quanto dare il consenso, quindi è consigliabile lasciarlo attivo.',
    'cc_save' => 'Salva',
    'cc_example_title' => 'Esempio: carica GA solo dopo il consenso',
    'cc_example_note' => 'Con Consent Mode v2 attivo puoi anche caricare gtag.js sempre — Google passa a ping senza cookie in base ai segnali di consenso.',
    'cc_log_update' => 'Impostazioni consenso cookie aggiornate',
];
