<?php
/**
 * YikaiCMS - Korean language pack (ko).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'cc_title' => 'Cookie 동의 배너',
    'cc_desc' => 'GDPR / PIPL 준수: 3단계 동의(필수/분석/마케팅) + 언제든지 철회할 수 있는 진입점. 기타 스크립트는 :api1 또는 :api2 이벤트로 카테고리별 로드를 제어합니다(PHP 측은 :api3).',
    'cc_policy_url' => '개인정보 처리방침 링크',
    'cc_policy_tip' => '입력하면 배너 본문에 “개인정보 처리방침” 링크가 표시됩니다(GDPR상 입력 권장).',
    'cc_policy_ver' => '정책 버전',
    'cc_policy_ver_tip' => 'Cookie 사용 방식이나 개인정보 처리방침이 실질적으로 변경되면 :b+1:_b 하세요. 모든 방문자의 기존 동의가 무효화되고 배너가 다시 표시되어 동의를 구합니다.',
    'cc_consent_mode' => 'Google Consent Mode v2 사용',
    'cc_consent_mode_tip' => 'gtag에 consent default/update 신호를 전송합니다(analytics_storage / ad_storage / ad_user_data / ad_personalization).',
    'cc_footer_link' => '“Cookie 설정” 상시 진입점 표시(왼쪽 아래)',
    'cc_footer_link_tip' => '방문자가 언제든지 동의를 철회하거나 변경할 수 있게 합니다. GDPR 제7조 3항은 철회를 동의만큼 쉽게 할 것을 요구하므로, 사용을 유지할 것을 권장합니다.',
    'cc_save' => '저장',
    'cc_example_title' => '연동 예: 동의 후 GA 로드',
    'cc_example_note' => 'Consent Mode v2를 사용 중이라면 gtag.js를 항상 로드해도 됩니다. Google이 consent 신호에 따라 쿠키 없는 ping으로 자동 전환합니다.',
    'cc_log_update' => 'Cookie 동의 설정을 업데이트했습니다',
];
