<?php
/**
 * YikaiCMS - Malay language pack (ms).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'cc_title' => 'Sepanduk persetujuan cookie',
    'cc_desc' => 'Sedia GDPR / PIPL: tiga kategori persetujuan (perlu, analitik, pemasaran) serta laluan tarik balik kekal. Skrip lain boleh mengawal pemuatan mengikut kategori melalui :api1 atau peristiwa :api2 (:api3 di sisi PHP).',
    'cc_policy_url' => 'Pautan dasar privasi',
    'cc_policy_tip' => 'Apabila ditetapkan, sepanduk menunjukkan pautan kepada dasar privasi anda. GDPR secara praktikal memerlukannya.',
    'cc_policy_ver' => 'Versi dasar',
    'cc_policy_ver_tip' => 'Naikkan :b+1:_b ini apabila penggunaan cookie atau dasar privasi berubah secara ketara. Semua persetujuan sedia ada menjadi tidak sah dan sepanduk meminta semula.',
    'cc_consent_mode' => 'Dayakan Google Consent Mode v2',
    'cc_consent_mode_tip' => 'Menghantar isyarat default/kemas kini consent kepada gtag (analytics_storage / ad_storage / ad_user_data / ad_personalization).',
    'cc_footer_link' => 'Tunjukkan entri "Tetapan cookie" kekal (bawah kiri)',
    'cc_footer_link_tip' => 'Membolehkan pelawat menarik balik atau menukar persetujuan pada bila-bila masa. GDPR Art. 7(3) menghendaki penarikan balik semudah memberi persetujuan, jadi biarkan ini dihidupkan.',
    'cc_save' => 'Simpan',
    'cc_example_title' => 'Contoh: muatkan GA hanya selepas persetujuan',
    'cc_example_note' => 'Dengan Consent Mode v2 dihidupkan anda juga boleh memuatkan gtag.js tanpa syarat — Google menurun kepada ping tanpa cookie berdasarkan isyarat persetujuan.',
    'cc_log_update' => 'Tetapan persetujuan cookie dikemas kini',
];
