<?php
/**
 * YikaiCMS - Brazilian Portuguese language pack (pt).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'cc_title' => 'Banner de consentimento de cookies',
    'cc_desc' => 'Conformidade com GDPR / PIPL: três categorias de consentimento (necessários, análise e marketing) e acesso permanente para revogá-lo. Outros scripts podem controlar o carregamento por categoria com :api1 ou o evento :api2 (no PHP, use :api3).',
    'cc_policy_url' => 'Link da política de privacidade',
    'cc_policy_tip' => 'Ao preencher, o texto do banner exibe o link “Política de privacidade”. Recomendamos preenchê-lo para o GDPR.',
    'cc_policy_ver' => 'Versão da política',
    'cc_policy_ver_tip' => 'Incremente :b+1:_b quando houver mudanças relevantes no uso de cookies ou na política de privacidade. Os consentimentos anteriores de todos os visitantes serão invalidados, e o banner solicitará consentimento novamente.',
    'cc_consent_mode' => 'Ativar Google Consent Mode v2',
    'cc_consent_mode_tip' => 'Envia sinais consent default/update ao gtag (analytics_storage / ad_storage / ad_user_data / ad_personalization).',
    'cc_footer_link' => 'Exibir acesso permanente a “Configurações de cookies” (canto inferior esquerdo)',
    'cc_footer_link_tip' => 'Permite que os visitantes revoguem ou alterem o consentimento a qualquer momento. O artigo 7(3) do GDPR exige que revogar seja tão fácil quanto consentir. Recomendamos manter esta opção ativada.',
    'cc_save' => 'Salvar',
    'cc_example_title' => 'Exemplo de integração: carregar GA após o consentimento',
    'cc_example_note' => 'Com Consent Mode v2 ativado, você também pode carregar gtag.js continuamente. O Google passa a usar pings sem cookies conforme os sinais de consentimento.',
    'cc_log_update' => 'Configurações de consentimento de cookies atualizadas',
];
