<?php
/**
 * YikaiCMS - Thai language pack (th).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'cc_title' => 'แบนเนอร์ความยินยอม Cookie',
    'cc_desc' => 'รองรับ GDPR / PIPL: การยินยอมสามระดับ (จำเป็น/วิเคราะห์/การตลาด) พร้อมทางเข้าการเพิกถอนตลอดเวลา สคริปต์อื่นสามารถควบคุมการโหลดตามหมวดหมู่ผ่าน :api1 หรือเหตุการณ์ :api2 (ฝั่ง PHP ใช้ :api3)',
    'cc_policy_url' => 'ลิงก์นโยบายความเป็นส่วนตัว',
    'cc_policy_tip' => 'เมื่อกรอกแล้ว แบนเนอร์จะแสดงลิงก์ "นโยบายความเป็นส่วนตัว" (GDPR แนะนำให้กรอก)',
    'cc_policy_ver' => 'เวอร์ชันนโยบาย',
    'cc_policy_ver_tip' => 'เพิ่ม :b+1:_b เมื่อมีการเปลี่ยนแปลงที่สำคัญเกี่ยวกับการใช้ Cookie หรือนโยบายความเป็นส่วนตัว ความยินยอมเดิมของผู้เข้าชมทั้งหมดจะถูกยกเลิก และแบนเนอร์จะแสดงอีกครั้งเพื่อขอความยินยอม',
    'cc_consent_mode' => 'เปิดใช้ Google Consent Mode v2',
    'cc_consent_mode_tip' => 'ส่งสัญญาณ consent default/update ไปยัง gtag (analytics_storage / ad_storage / ad_user_data / ad_personalization)',
    'cc_footer_link' => 'แสดงทางเข้า "การตั้งค่า Cookie" แบบถาวร (มุมล่างซ้าย)',
    'cc_footer_link_tip' => 'ให้ผู้เข้าชมเพิกถอนหรือเปลี่ยนความยินยอมได้ตลอดเวลา GDPR มาตรา 7(3) กำหนดให้การเพิกถอนทำได้ง่ายพอ ๆ กับการให้ความยินยอม จึงแนะนำให้เปิดใช้งานไว้',
    'cc_save' => 'บันทึก',
    'cc_example_title' => 'ตัวอย่าง: โหลด GA หลังได้รับความยินยอม',
    'cc_example_note' => 'หากเปิดใช้ Consent Mode v2 คุณก็โหลด gtag.js แบบถาวรได้ Google จะลดระดับเป็น ping แบบไม่มี Cookie ตามสัญญาณ consent',
    'cc_log_update' => 'อัปเดตการตั้งค่าความยินยอม Cookie',
];
