<?php
/**
 * YikaiCMS - Turkish language pack (tr).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'cc_title' => 'Cookie onay bandı',
    'cc_desc' => 'GDPR / PIPL uyumlu: üç onay kategorisi (zorunlu, analitik, pazarlama) ve kalıcı geri çekme girişi. Diğer betikler :api1 veya :api2 olayıyla kategoriye göre yüklemeyi denetleyebilir (PHP tarafında :api3).',
    'cc_policy_url' => 'Gizlilik politikası bağlantısı',
    'cc_policy_tip' => 'Ayarlanınca bant gizlilik politikanıza bir bağlantı gösterir. GDPR bunu neredeyse zorunlu kılar.',
    'cc_policy_ver' => 'Politika sürümü',
    'cc_policy_ver_tip' => 'Cookie kullanımınız veya gizlilik politikanız esaslı biçimde değiştiğinde bunu :b+1:_b artırın. Mevcut tüm onaylar geçersiz olur ve bant yeniden sorar.',
    'cc_consent_mode' => 'Google Consent Mode v2\'yi etkinleştir',
    'cc_consent_mode_tip' => 'gtag\'e consent default/update sinyalleri gönderir (analytics_storage / ad_storage / ad_user_data / ad_personalization).',
    'cc_footer_link' => 'Kalıcı Cookie ayarları girişi göster (sol alt)',
    'cc_footer_link_tip' => 'Ziyaretçilerin onayı istedikleri zaman geri çekmesine veya değiştirmesine izin verir. GDPR md. 7(3), geri çekmenin vermek kadar kolay olmasını gerektirir; açık tutun.',
    'cc_save' => 'Kaydet',
    'cc_example_title' => 'Örnek: GA\'yı yalnızca onaydan sonra yükle',
    'cc_example_note' => 'Consent Mode v2 etkinse gtag.js\'i koşulsuz da yükleyebilirsiniz — Google onay sinyallerine göre cookie\'siz pinglere geçer.',
    'cc_log_update' => 'Cookie onay ayarları güncellendi',
];
