<?php
/**
 * YikaiCMS - Vietnamese language pack (vi).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'cc_title' => 'Banner đồng ý Cookie',
    'cc_desc' => 'Tuân thủ GDPR / PIPL: ba mức đồng ý (thiết yếu/phân tích/tiếp thị) + lối vào để rút lại bất cứ lúc nào. Các script khác dùng :api1 hoặc sự kiện :api2 để kiểm soát tải theo danh mục (phía PHP dùng :api3).',
    'cc_policy_url' => 'Liên kết chính sách bảo mật',
    'cc_policy_tip' => 'Sau khi điền, banner sẽ hiển thị liên kết “Chính sách bảo mật” trong phần nội dung (GDPR khuyến nghị bắt buộc).',
    'cc_policy_ver' => 'Số phiên bản chính sách',
    'cc_policy_ver_tip' => 'Khi cách dùng Cookie hoặc chính sách bảo mật có thay đổi thực chất, hãy :b+1:_b: mọi đồng ý cũ của khách sẽ hết hiệu lực và banner hiện lại để xin đồng ý.',
    'cc_consent_mode' => 'Bật Google Consent Mode v2',
    'cc_consent_mode_tip' => 'Phát tín hiệu consent default/update tới gtag (analytics_storage / ad_storage / ad_user_data / ad_personalization).',
    'cc_footer_link' => 'Hiển thị lối vào “Cài đặt Cookie” thường trực (góc dưới bên trái)',
    'cc_footer_link_tip' => 'Cho phép khách rút lại hoặc thay đổi đồng ý bất cứ lúc nào — Điều 7(3) GDPR yêu cầu việc rút lại phải dễ như khi đưa ra, nên giữ bật.',
    'cc_save' => 'Lưu',
    'cc_example_title' => 'Ví dụ tích hợp: tải GA theo mức đồng ý',
    'cc_example_note' => 'Nếu đã bật Consent Mode v2, bạn cũng có thể tải gtag.js thường trực — Google sẽ tự hạ cấp theo tín hiệu consent (ping không Cookie).',
    'cc_log_update' => 'Đã cập nhật cấu hình đồng ý Cookie',
];
