<?php
/**
 * YikaiCMS - Traditional Chinese (Taiwan) language pack (zh-TW).
 * Generated by tools/i18n/zh-tw.php from zh-CN via OpenCC; reviewed wording is kept while the zh-CN source is unchanged.
 * Content is not here: it stays in Simplified Chinese and the front end converts each page.
 */

return [
    'cc_title' => 'Cookie 同意橫幅',
    'cc_desc' => 'GDPR / PIPL 合規：三檔授權（必要/分析/營銷）+ 隨時撤回入口。其他指令碼用 :api1 或 :api2 事件按類別門控載入（PHP 端用 :api3）。',
    'cc_policy_url' => '隱私政策連結',
    'cc_policy_tip' => '填寫後橫幅正文中顯示「隱私政策」連結（GDPR 建議必填）。',
    'cc_policy_ver' => '政策版本號',
    'cc_policy_ver_tip' => 'Cookie 使用方式或隱私政策有實質變更時 :b+1:_b：所有訪客的舊同意即失效，橫幅重新彈出徵求同意。',
    'cc_consent_mode' => '啟用 Google Consent Mode v2',
    'cc_consent_mode_tip' => '向 gtag 輸出 consent default/update 訊號（analytics_storage / ad_storage / ad_user_data / ad_personalization）。',
    'cc_footer_link' => '顯示「Cookie 設定」常駐入口（左下角）',
    'cc_footer_link_tip' => '讓訪客隨時撤回或變更同意——GDPR 第 7(3) 條要求撤回同意與給出同意同樣容易，建議保持開啟。',
    'cc_save' => '儲存',
    'cc_example_title' => '接入示例：按同意載入 GA',
    'cc_example_note' => '若啟用了 Consent Mode v2，也可以直接常載 gtag.js——Google 會按 consent 訊號自行降級（無 Cookie 的 ping）。',
    'cc_log_update' => '更新 Cookie 同意配置',
];
