<?php
declare(strict_types=1);

/** Canonical portable site-template schema for CMS 2.0.0. */
return array (
  'channels' =>
  array (
    0 => 'album_id',
    1 => 'content',
    2 => 'created_at',
    3 => 'description',
    4 => 'hero_bg',
    5 => 'hero_style_options',
    6 => 'hero_style_source',
    7 => 'icon',
    8 => 'id',
    9 => 'image',
    10 => 'is_home',
    11 => 'is_nav',
    12 => 'is_system',
    13 => 'lang',
    14 => 'link_target',
    15 => 'link_url',
    16 => 'list_options',
    17 => 'name',
    18 => 'parent_id',
    19 => 'redirect_type',
    20 => 'redirect_url',
    21 => 'seo_description',
    22 => 'seo_keywords',
    23 => 'seo_title',
    24 => 'show_cover',
    25 => 'show_hero',
    26 => 'show_sidebar',
    27 => 'slug',
    28 => 'sort_order',
    29 => 'status',
    30 => 'translation_group_id',
    31 => 'type',
    32 => 'updated_at',
  ),
  'contents' =>
  array (
    0 => 'admin_id',
    1 => 'attachment',
    2 => 'author',
    3 => 'blocks_data',
    4 => 'channel_id',
    5 => 'client_name',
    6 => 'content',
    7 => 'content_type',
    8 => 'cover',
    9 => 'created_at',
    10 => 'deleted_at',
    11 => 'download_count',
    12 => 'duration',
    13 => 'education',
    14 => 'experience',
    15 => 'headcount',
    16 => 'id',
    17 => 'images',
    18 => 'industry',
    19 => 'is_hot',
    20 => 'is_recommend',
    21 => 'is_top',
    22 => 'job_type',
    23 => 'lang',
    24 => 'likes',
    25 => 'location',
    26 => 'price',
    27 => 'publish_time',
    28 => 'requirements',
    29 => 'result_metric',
    30 => 'salary',
    31 => 'seo_description',
    32 => 'seo_keywords',
    33 => 'seo_title',
    34 => 'slug',
    35 => 'sort_order',
    36 => 'source',
    37 => 'specs',
    38 => 'status',
    39 => 'subtitle',
    40 => 'summary',
    41 => 'tags',
    42 => 'title',
    43 => 'translation_group_id',
    44 => 'type',
    45 => 'updated_at',
    46 => 'views',
  ),
  'product_categories' =>
  array (
    0 => 'created_at',
    1 => 'description',
    2 => 'id',
    3 => 'image',
    4 => 'is_nav',
    5 => 'lang',
    6 => 'name',
    7 => 'parent_id',
    8 => 'seo_description',
    9 => 'seo_keywords',
    10 => 'seo_title',
    11 => 'slug',
    12 => 'sort_order',
    13 => 'status',
    14 => 'translation_group_id',
  ),
  'brands' =>
  array (
    0 => 'country',
    1 => 'description',
    2 => 'id',
    3 => 'lang',
    4 => 'logo',
    5 => 'name',
    6 => 'slug',
    7 => 'sort_order',
    8 => 'status',
    9 => 'translation_group_id',
    10 => 'url',
  ),
  'products' =>
  array (
    0 => 'admin_id',
    1 => 'brand_id',
    2 => 'category_id',
    3 => 'content',
    4 => 'cover',
    5 => 'created_at',
    6 => 'deleted_at',
    7 => 'id',
    8 => 'images',
    9 => 'is_hot',
    10 => 'is_new',
    11 => 'is_recommend',
    12 => 'is_top',
    13 => 'lang',
    14 => 'market_price',
    15 => 'material',
    16 => 'model',
    17 => 'price',
    18 => 'product_type',
    19 => 'scene',
    20 => 'slug',
    21 => 'sort_order',
    22 => 'specs',
    23 => 'status',
    24 => 'subtitle',
    25 => 'summary',
    26 => 'tags',
    27 => 'title',
    28 => 'translation_group_id',
    29 => 'updated_at',
    30 => 'views',
  ),
  'product_tags' =>
  array (
    0 => 'group_name',
    1 => 'id',
    2 => 'lang',
    3 => 'name',
    4 => 'slug',
    5 => 'sort_order',
    6 => 'status',
    7 => 'translation_group_id',
  ),
  'product_tag_map' =>
  array (
    0 => 'product_id',
    1 => 'tag_id',
  ),
  'product_routes' =>
  array (
    0 => 'entity_id',
    1 => 'entity_type',
    2 => 'id',
    3 => 'path',
    4 => 'path_key',
  ),
  'albums' =>
  array (
    0 => 'category_id',
    1 => 'cover',
    2 => 'created_at',
    3 => 'deleted_at',
    4 => 'description',
    5 => 'id',
    6 => 'lang',
    7 => 'layout',
    8 => 'name',
    9 => 'photo_count',
    10 => 'slug',
    11 => 'sort_order',
    12 => 'status',
    13 => 'translation_group_id',
    14 => 'updated_at',
  ),
  'album_photos' =>
  array (
    0 => 'album_id',
    1 => 'created_at',
    2 => 'description',
    3 => 'id',
    4 => 'image',
    5 => 'sort_order',
    6 => 'status',
    7 => 'thumb',
    8 => 'title',
  ),
  'download_categories' =>
  array (
    0 => 'created_at',
    1 => 'description',
    2 => 'id',
    3 => 'name',
    4 => 'name_en',
    5 => 'name_ja',
    6 => 'slug',
    7 => 'sort_order',
    8 => 'status',
  ),
  'downloads' =>
  array (
    0 => 'admin_id',
    1 => 'category_id',
    2 => 'cover',
    3 => 'created_at',
    4 => 'deleted_at',
    5 => 'description',
    6 => 'download_count',
    7 => 'file_ext',
    8 => 'file_name',
    9 => 'file_size',
    10 => 'file_url',
    11 => 'id',
    12 => 'is_external',
    13 => 'lang',
    14 => 'require_login',
    15 => 'sort_order',
    16 => 'status',
    17 => 'title',
    18 => 'translation_group_id',
    19 => 'updated_at',
  ),
  'jobs' =>
  array (
    0 => 'admin_id',
    1 => 'content',
    2 => 'cover',
    3 => 'created_at',
    4 => 'deleted_at',
    5 => 'education',
    6 => 'experience',
    7 => 'headcount',
    8 => 'id',
    9 => 'is_top',
    10 => 'job_type',
    11 => 'lang',
    12 => 'location',
    13 => 'publish_time',
    14 => 'requirements',
    15 => 'salary',
    16 => 'sort_order',
    17 => 'status',
    18 => 'summary',
    19 => 'title',
    20 => 'translation_group_id',
    21 => 'updated_at',
    22 => 'views',
  ),
  'timelines' =>
  array (
    0 => 'color',
    1 => 'content',
    2 => 'created_at',
    3 => 'day',
    4 => 'icon',
    5 => 'id',
    6 => 'image',
    7 => 'lang',
    8 => 'month',
    9 => 'sort_order',
    10 => 'status',
    11 => 'title',
    12 => 'translation_group_id',
    13 => 'updated_at',
    14 => 'year',
  ),
  'links' =>
  array (
    0 => 'created_at',
    1 => 'description',
    2 => 'id',
    3 => 'lang',
    4 => 'logo',
    5 => 'name',
    6 => 'sort_order',
    7 => 'status',
    8 => 'translation_group_id',
    9 => 'url',
  ),
  'banner_groups' =>
  array (
    0 => 'autoplay_delay',
    1 => 'background_motion',
    2 => 'content_motion',
    3 => 'created_at',
    4 => 'effect',
    5 => 'fullscreen',
    6 => 'height_mobile',
    7 => 'height_mode',
    8 => 'height_pc',
    9 => 'id',
    10 => 'name',
    11 => 'navigation',
    12 => 'pagination',
    13 => 'pause_hover',
    14 => 'slug',
    15 => 'sort_order',
    16 => 'speed',
    17 => 'stagger',
    18 => 'status',
  ),
  'banners' =>
  array (
    0 => 'background_motion',
    1 => 'btn1_text',
    2 => 'btn1_url',
    3 => 'btn2_text',
    4 => 'btn2_url',
    5 => 'content_motion',
    6 => 'created_at',
    7 => 'end_time',
    8 => 'id',
    9 => 'image',
    10 => 'image_mobile',
    11 => 'lang',
    12 => 'link_target',
    13 => 'link_url',
    14 => 'media_type',
    15 => 'position',
    16 => 'sort_order',
    17 => 'start_time',
    18 => 'status',
    19 => 'subtitle',
    20 => 'title',
    21 => 'translation_group_id',
    22 => 'video',
    23 => 'video_mobile_mode',
  ),
  'nav_menus' =>
  array (
    0 => 'created_at',
    1 => 'id',
    2 => 'items',
    3 => 'name',
    4 => 'sort_order',
    5 => 'updated_at',
  ),
  'form_templates' =>
  array (
    0 => 'captcha',
    1 => 'created_at',
    2 => 'fields',
    3 => 'fields_en',
    4 => 'fields_ja',
    5 => 'id',
    6 => 'name',
    7 => 'name_en',
    8 => 'name_ja',
    9 => 'slug',
    10 => 'status',
    11 => 'success_message',
    12 => 'success_message_en',
    13 => 'success_message_ja',
  ),
  'content_models' =>
  array (
    0 => 'created_at',
    1 => 'detail_template',
    2 => 'has_detail',
    3 => 'icon',
    4 => 'id',
    5 => 'list_template',
    6 => 'model_key',
    7 => 'name',
    8 => 'name_en',
    9 => 'name_ja',
    10 => 'sort_order',
    11 => 'status',
    12 => 'url_prefix',
  ),
  'extfields' =>
  array (
    0 => 'created_at',
    1 => 'field_key',
    2 => 'field_name',
    3 => 'field_type',
    4 => 'help_text',
    5 => 'id',
    6 => 'is_required',
    7 => 'options',
    8 => 'owner_type',
    9 => 'placeholder',
    10 => 'sort_order',
    11 => 'status',
  ),
  'metas' =>
  array (
    0 => 'created_at',
    1 => 'id',
    2 => 'meta_key',
    3 => 'meta_value',
    4 => 'owner_id',
    5 => 'owner_type',
    6 => 'updated_at',
  ),
  'media' =>
  array (
    0 => 'admin_id',
    1 => 'created_at',
    2 => 'ext',
    3 => 'height',
    4 => 'id',
    5 => 'md5',
    6 => 'mime',
    7 => 'name',
    8 => 'path',
    9 => 'size',
    10 => 'type',
    11 => 'url',
    12 => 'width',
  ),
  'blocks_library' =>
  array (
    0 => 'created_at',
    1 => 'data',
    2 => 'id',
    3 => 'name',
    4 => 'updated_at',
  ),
  'blox_templates' =>
  array (
    0 => 'admin_id',
    1 => 'conditions',
    2 => 'created_at',
    3 => 'draft_data',
    4 => 'id',
    5 => 'metadata',
    6 => 'name',
    7 => 'published_at',
    8 => 'published_data',
    9 => 'requirements',
    10 => 'schema_version',
    11 => 'source',
    12 => 'source_ref',
    13 => 'status',
    14 => 'thumbnail',
    15 => 'type',
    16 => 'updated_at',
  ),
  'blox_global_classes' =>
  array (
    0 => 'category',
    1 => 'class_id',
    2 => 'created_at',
    3 => 'id',
    4 => 'modified',
    5 => 'name',
    6 => 'revision',
    7 => 'settings',
    8 => 'status',
    9 => 'trashed_at',
    10 => 'updated_at',
    11 => 'user_id',
  ),
  'blox_global_queries' =>
  array (
    0 => 'created_at',
    1 => 'id',
    2 => 'modified',
    3 => 'name',
    4 => 'query',
    5 => 'query_id',
    6 => 'updated_at',
    7 => 'user_id',
  ),
  'blox_class_refs' =>
  array (
    0 => 'class_id',
    1 => 'doc_key',
    2 => 'id',
    3 => 'ref_count',
    4 => 'updated_at',
  ),
  'blox_query_refs' =>
  array (
    0 => 'doc_key',
    1 => 'id',
    2 => 'query_id',
    3 => 'ref_count',
    4 => 'updated_at',
  ),
);
