<?php
/**
 * 合入人工 / AI 审校过的繁体界面文案：php tools/i18n/zh-tw-apply.php [--dry-run] <review.jsonl>...
 *
 * 每行 {"file","key","zh_cn","zh_tw","proposed"}（导出见 handoffs 任务单）。逐条校验后写入对应的 zh-TW.php：
 * - 简体原文或当前繁体已和导出时不同 → 跳过（STALE），需要重新导出审校；
 * - proposed 与当前繁体的占位符（:name、%s、{x}）或 HTML 标签不一致 → 拒绝；
 * - proposed 含简体字（简→繁转换会改动的单字；「台」在台湾通用，不算）→ 拒绝；
 * - 前台还会整页再转一次：proposed 必须是转换的不动点，否则列出（REPASS），需在 S2T 保留表里补词。
 * 写入后重跑 tools/i18n/zh-tw.php 记下原文哈希，审过的写法在简体原文不变时一直保留。
 */
declare(strict_types=1);
require __DIR__ . '/_cli.php';

$root = dirname(__DIR__, 2);
define('ROOT_PATH', $root);
require_once $root . '/includes/i18n/S2T.php';
[$files, $opt] = i18n_args($argv);
$dry = isset($opt['dry-run']);
if ($files === [] || !S2T::available()) {
    fwrite(STDERR, "Usage: php tools/i18n/zh-tw-apply.php [--dry-run] <review.jsonl>...\n");
    exit(2);
}

$pipeline = i18n_pipeline();
$tokens = static function (string $s): array {
    preg_match_all('/:[a-z_]+|%[sd]|\{\{?[^}]+\}\}?|<[^>]+>|&[a-z#0-9]+;/i', $s, $m);
    $t = $m[0];
    sort($t);
    return $t;
};
$packs = [];
$count = ['ok' => 0, 'same' => 0, 'stale' => 0, 'rejected' => 0, 'repass' => 0];
foreach ($files as $path) {
    foreach (I18nPipeline::readJsonl($path) as $row) {
        $file = (string) ($row['file'] ?? '');
        $key = (string) ($row['key'] ?? '');
        $proposed = (string) ($row['proposed'] ?? '');
        if (preg_match('#^(lang|plugins/[a-z0-9-]+/lang)/zh-TW\.php$#D', $file) !== 1 || $key === '' || $proposed === '') {
            echo "REJECT bad row: {$file} {$key}\n";
            $count['rejected']++;
            continue;
        }
        $dir = dirname($file);
        $packs[$file] ??= ['zh' => $pipeline->load("{$dir}/zh-CN.php"), 'tw' => $pipeline->load($file), 'changed' => false];
        $zh = $packs[$file]['zh'][$key] ?? null;
        $tw = $packs[$file]['tw'][$key] ?? null;
        if ($zh !== ($row['zh_cn'] ?? null) || $tw !== ($row['zh_tw'] ?? null)) {
            echo "STALE {$file} {$key}\n";
            $count['stale']++;
            continue;
        }
        if ($proposed === $tw) {
            $count['same']++;
            continue;
        }
        if ($tokens($proposed) !== $tokens((string) $tw)) {
            echo "REJECT placeholders/tags {$file} {$key}: {$proposed}\n";
            $count['rejected']++;
            continue;
        }
        $simplified = array_filter(mb_str_split($proposed), static fn (string $c): bool => $c !== '台' && S2T::text($c) !== $c && preg_match('/\p{Han}/u', $c) === 1);
        $once = S2T::text($proposed);
        if ($once !== $proposed) {
            // 只是单字转换（含简体字）还是词组被再次改写，分开报
            if ($simplified !== []) {
                echo "REJECT simplified chars (" . implode('', array_unique($simplified)) . ") {$file} {$key}: {$proposed}\n";
                $count['rejected']++;
                continue;
            }
            echo "REPASS {$file} {$key}: {$proposed} => {$once}\n";
            $count['repass']++;
        }
        $packs[$file]['tw'][$key] = $proposed;
        $packs[$file]['changed'] = true;
        $count['ok']++;
    }
}
echo json_encode($count) . "\n";
if ($dry) {
    exit(0);
}
foreach ($packs as $file => $pack) {
    if (!$pack['changed']) {
        continue;
    }
    $lines = ['<?php', '/**', ' * YikaiCMS - Traditional Chinese (Taiwan) language pack (zh-TW).',
        ' * Generated by tools/i18n/zh-tw.php from zh-CN via OpenCC; reviewed wording is kept while the zh-CN source is unchanged.',
        ' * Content is not here: it stays in Simplified Chinese and the front end converts each page.', ' */', '', 'return ['];
    foreach ($pack['zh'] as $key => $zh) {
        if (is_string($zh) && isset($pack['tw'][$key])) {
            $lines[] = '    ' . I18nPipeline::phpString((string) $key) . ' => ' . I18nPipeline::phpString((string) $pack['tw'][$key]) . ',';
        }
    }
    $lines[] = '];';
    file_put_contents("{$root}/{$file}", implode("\n", $lines) . "\n");
    echo "wrote {$file}\n";
}
