<?php
/**
 * 生成繁體中文界面语言包：php tools/i18n/zh-tw.php [--check]
 *
 * 界面文案（核心 lang/ 与仓库内插件的 lang/）从 zh-CN 经 OpenCC 词库（includes/i18n/s2t_maps.php）
 * 转成繁体（台湾用词），写到 zh-TW.php。内容不在这里——内容仍是一份简体，前台输出时整页转换。
 *
 * - 已有译文在简体原文没变时保留（人工或 AI 审过的用词不会被下次生成覆盖）；原文变了的重新转换。
 *   原文哈希记在 tools/i18n/hashes/zh-TW.json。
 * - 转到不再变化为止：前台还会整页再转一次，已是繁体的文案必须是转换的不动点。
 * - --check：只报告缺失或过期的键，有就退出码 1（不写文件）。
 */
declare(strict_types=1);
require __DIR__ . '/_cli.php';

$root = dirname(__DIR__, 2);
define('ROOT_PATH', $root);
require_once $root . '/includes/i18n/S2T.php';
if (!S2T::available()) {
    fwrite(STDERR, "Missing includes/i18n/s2t_maps.php (run tools/build-s2t-map.sh)\n");
    exit(2);
}
[, $opt] = i18n_args($argv);
$check = isset($opt['check']);

// 产品术语表（繁体用语审校结论）：新转换的文案先换术语再转繁体。
// 「主题」有主题 / 话题两种意思，不自动换，新文案里的「佈景主題」需人工审。
$glossaryFile = $root . '/tools/i18n/glossary/zh-TW.json';
$glossary = is_file($glossaryFile) ? (array) json_decode((string) file_get_contents($glossaryFile), true) : [];

/** 转到不动点（最多 4 趟） */
$convert = static function (string $text) use ($glossary): string {
    $text = strtr($text, $glossary);
    for ($i = 0; $i < 4; $i++) {
        $next = S2T::text($text);
        if ($next === $text) {
            break;
        }
        $text = $next;
    }
    return $text;
};

$hashFile = $root . '/tools/i18n/hashes/zh-TW.json';
$hashes = is_file($hashFile) ? (array) json_decode((string) file_get_contents($hashFile), true) : [];
$newHashes = [];
$units = ['lang' => 'lang'];
foreach (glob($root . '/plugins/*/lang/zh-CN.php') ?: [] as $src) {
    $dir = substr(dirname($src), strlen($root) + 1);
    $units[str_replace('\\', '/', $dir)] = str_replace('\\', '/', $dir);
}

$pipeline = i18n_pipeline();
$problems = 0;
foreach ($units as $dir) {
    $source = array_filter($pipeline->load("{$dir}/zh-CN.php"), 'is_string');
    $target = is_file("{$root}/{$dir}/zh-TW.php") ? $pipeline->load("{$dir}/zh-TW.php") : [];
    $values = [];
    $changed = 0;
    foreach ($source as $key => $zh) {
        $id = "{$dir}/zh-TW.php|{$key}";
        $hash = I18nPipeline::hash($zh);
        $newHashes[$id] = $hash;
        $have = $target[$key] ?? null;
        // 保留：原文没变（或尚未记哈希的手写覆盖）且已有译文
        if (is_string($have) && (($hashes[$id] ?? $hash) === $hash)) {
            $values[$key] = $have;
            continue;
        }
        $values[$key] = $convert($zh);
        $changed++;
    }
    if ($check) {
        if ($changed > 0) {
            echo "{$dir}/zh-TW.php: {$changed} missing or stale\n";
            $problems += $changed;
        }
        continue;
    }
    $lines = ['<?php', '/**', ' * YikaiCMS - Traditional Chinese (Taiwan) language pack (zh-TW).',
        ' * Generated by tools/i18n/zh-tw.php from zh-CN via OpenCC; reviewed wording is kept while the zh-CN source is unchanged.',
        ' * Content is not here: it stays in Simplified Chinese and the front end converts each page.', ' */', '', 'return ['];
    foreach ($values as $key => $value) {
        $lines[] = '    ' . I18nPipeline::phpString($key) . ' => ' . I18nPipeline::phpString($value) . ',';
    }
    $lines[] = '];';
    $path = "{$root}/{$dir}/zh-TW.php";
    file_put_contents($path, implode("\n", $lines) . "\n");
    exec(escapeshellarg(PHP_BINARY) . ' -l ' . escapeshellarg($path) . ' 2>&1', $out, $code);
    if ($code !== 0) {
        fwrite(STDERR, "Lint failed: {$dir}/zh-TW.php\n");
        exit(1);
    }
    echo "{$dir}/zh-TW.php: " . count($values) . " keys, {$changed} converted\n";
}
if ($check) {
    exit($problems > 0 ? 1 : 0);
}
ksort($newHashes);
file_put_contents($hashFile, json_encode($newHashes, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . "\n");
