<?php
/**
 * YikaiCMS - Arabic language pack (ar).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'mnsort_title' => 'ترتيب قائمة لوحة الإدارة',
    'mnsort_tip' => 'اسحب لإعادة الترتيب، وانقر على الاسم لإعادة تسميته، واستخدم 👁 للتبديل بين الإظهار والإخفاء. :bتُحفظ التغييرات تلقائيًا:_b وتصبح سارية بعد إعادة تحميل صفحة في لوحة الإدارة. تنطبق إعادة التسمية على لغة لوحة الإدارة الحالية فقط (:lang)؛ امسح الحقل لاستعادة الافتراضي.',
    'mnsort_reset' => 'استعادة الافتراضي',
    'mnsort_save_now' => 'احفظ الآن',
    'mnsort_toggle_group' => 'إظهار أو إخفاء المجموعة بأكملها',
    'mnsort_toggle_item' => 'إظهار / إخفاء',
    'mnsort_rename_tip' => 'تُحفظ إعادة التسمية فورًا. امسح الحقل لاستعادة الافتراضي.',
    'mnsort_saving' => 'جارٍ الحفظ…',
    'mnsort_autosaved' => '✓ تم الحفظ تلقائيًا ',
    'mnsort_saved_hint' => 'تم الحفظ. أعد تحميل صفحة في لوحة الإدارة لرؤية الشريط الجانبي الجديد.',
    'mnsort_save_failed' => 'فشل الحفظ',
    'mnsort_reset_confirm' => 'إعادة ترتيب القائمة إلى الافتراضي؟',
    'mnsort_reset_done' => 'تمت الاستعادة إلى الافتراضي',
    'mnsort_bad_data' => 'بيانات فرز غير صالحة',
    'mnsort_log_update' => 'تم تحديث ترتيب القائمة',
    'mnsort_log_reset' => 'تمت إعادة تعيين ترتيب القائمة',
    'mnsort_reset_msg' => 'تمت إعادة تعيين ترتيب القائمة إلى الافتراضي',
    'mnsort_grp_system' => 'النظام',
    'mnsort_grp_setting' => 'إعدادات الموقع',
    'mnsort_grp_plugin' => 'الإضافات',
    'mnsort_from_plugin' => 'الإضافة: ',
];
