<?php
/**
 * YikaiCMS - Spanish language pack (es).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'mnsort_title' => 'Orden del menú del panel de administración',
    'mnsort_tip' => 'Arrastre para ordenar, pulse un nombre para cambiarlo y utilice 👁 para mostrar u ocultar. :b Los cambios se guardan automáticamente :_b y se aplican al actualizar una página del panel de administración. Los nombres nuevos solo se aplican al idioma actual del panel de administración (:lang). Deje el campo vacío para recuperar el nombre predeterminado.',
    'mnsort_reset' => 'Restaurar valores predeterminados',
    'mnsort_save_now' => 'Guardar ahora',
    'mnsort_toggle_group' => 'Mostrar/ocultar todo el grupo',
    'mnsort_toggle_item' => 'Mostrar/ocultar',
    'mnsort_rename_tip' => 'El nombre se guarda inmediatamente. Deje el campo vacío para recuperar el nombre predeterminado.',
    'mnsort_saving' => 'Guardando…',
    'mnsort_autosaved' => '✓ Guardado automáticamente ',
    'mnsort_saved_hint' => 'Guardado. Actualice una página del panel de administración para aplicar los cambios de la barra lateral.',
    'mnsort_save_failed' => 'No se ha podido guardar',
    'mnsort_reset_confirm' => '¿Restaurar el orden predeterminado del menú?',
    'mnsort_reset_done' => 'Valores predeterminados restaurados',
    'mnsort_bad_data' => 'Los datos de orden no son válidos',
    'mnsort_log_update' => 'Se ha actualizado la configuración del orden del menú',
    'mnsort_log_reset' => 'Se ha restablecido el orden del menú',
    'mnsort_reset_msg' => 'Se ha restaurado el orden predeterminado',
    'mnsort_grp_system' => 'Sistema',
    'mnsort_grp_setting' => 'Configuración del sitio',
    'mnsort_grp_plugin' => 'Plugins',
    'mnsort_from_plugin' => 'Plugin: ',
];
