<?php
/**
 * YikaiCMS - French language pack (fr).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'mnsort_title' => 'Tri du menu d’administration',
    'mnsort_tip' => 'Faites glisser pour réorganiser, cliquez sur un nom pour le renommer et utilisez 👁 pour l’afficher ou le masquer. :b Les modifications sont enregistrées automatiquement :_b et prennent effet après le rechargement d’une page d’administration. Le renommage ne concerne que la langue d’administration actuelle (:lang) ; videz le champ pour rétablir le nom par défaut.',
    'mnsort_reset' => 'Rétablir l’ordre par défaut',
    'mnsort_save_now' => 'Enregistrer maintenant',
    'mnsort_toggle_group' => 'Afficher ou masquer tout ce groupe',
    'mnsort_toggle_item' => 'Afficher ou masquer',
    'mnsort_rename_tip' => 'Le nouveau nom est enregistré immédiatement. Videz le champ pour rétablir le nom par défaut.',
    'mnsort_saving' => 'Enregistrement…',
    'mnsort_autosaved' => '✓ Enregistré ',
    'mnsort_saved_hint' => 'Enregistré. Rechargez une page d’administration pour voir la nouvelle barre latérale.',
    'mnsort_save_failed' => 'Échec de l’enregistrement',
    'mnsort_reset_confirm' => 'Rétablir l’ordre du menu par défaut ?',
    'mnsort_reset_done' => 'Ordre par défaut rétabli',
    'mnsort_bad_data' => 'Données de tri invalides',
    'mnsort_log_update' => 'Ordre du menu mis à jour',
    'mnsort_log_reset' => 'Ordre du menu rétabli',
    'mnsort_reset_msg' => 'Ordre du menu rétabli par défaut',
    'mnsort_grp_system' => 'Système',
    'mnsort_grp_setting' => 'Réglages du site',
    'mnsort_grp_plugin' => 'Extensions',
    'mnsort_from_plugin' => 'Extension : ',
];
