<?php
/**
 * YikaiCMS - Indonesian language pack (id).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'mnsort_title' => 'Urutkan Menu Panel Admin',
    'mnsort_tip' => 'Seret untuk mengurutkan, klik nama untuk mengganti nama, dan gunakan 👁 untuk menampilkan atau menyembunyikan. :b Perubahan tersimpan otomatis :_b dan berlaku setelah Anda memuat ulang halaman panel admin. Penggantian nama hanya berlaku untuk bahasa panel admin saat ini (:lang); kosongkan untuk memulihkan default.',
    'mnsort_reset' => 'Pulihkan default',
    'mnsort_save_now' => 'Simpan sekarang',
    'mnsort_toggle_group' => 'Tampilkan/sembunyikan seluruh grup',
    'mnsort_toggle_item' => 'Tampilkan/sembunyikan',
    'mnsort_rename_tip' => 'Mengganti nama langsung tersimpan; kosongkan untuk memulihkan default.',
    'mnsort_saving' => 'Menyimpan…',
    'mnsort_autosaved' => '✓ Tersimpan otomatis ',
    'mnsort_saved_hint' => 'Tersimpan. Muat ulang halaman panel admin untuk melihat bilah sisi baru.',
    'mnsort_save_failed' => 'Gagal menyimpan',
    'mnsort_reset_confirm' => 'Pulihkan urutan menu ke default?',
    'mnsort_reset_done' => 'Dipulihkan ke default',
    'mnsort_bad_data' => 'Data urutan tidak valid',
    'mnsort_log_update' => 'Memperbarui urutan menu',
    'mnsort_log_reset' => 'Mereset urutan menu',
    'mnsort_reset_msg' => 'Urutan menu dipulihkan ke default',
    'mnsort_grp_system' => 'Sistem',
    'mnsort_grp_setting' => 'Pengaturan situs',
    'mnsort_grp_plugin' => 'Plugin',
    'mnsort_from_plugin' => 'Plugin: ',
];
