<?php
/**
 * YikaiCMS - Italian language pack (it).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'mnsort_title' => 'Ordinamento menu admin',
    'mnsort_tip' => 'Trascina per riordinare, fai clic su un nome per rinominarlo e usa 👁 per mostrare o nascondere. :b Le modifiche si salvano automaticamente :_b e hanno effetto dopo il ricaricamento di una pagina del pannello. La rinomina vale solo per la lingua corrente del pannello (:lang); svuota il campo per ripristinare il valore predefinito.',
    'mnsort_reset' => 'Ripristina predefinito',
    'mnsort_save_now' => 'Salva ora',
    'mnsort_toggle_group' => 'Mostra o nascondi l\'intero gruppo',
    'mnsort_toggle_item' => 'Mostra o nascondi',
    'mnsort_rename_tip' => 'La rinomina si salva subito. Svuota il campo per ripristinare il valore predefinito.',
    'mnsort_saving' => 'Salvataggio…',
    'mnsort_autosaved' => '✓ Salvato ',
    'mnsort_saved_hint' => 'Salvato. Ricarica una pagina del pannello per aggiornare la barra laterale.',
    'mnsort_save_failed' => 'Salvataggio non riuscito',
    'mnsort_reset_confirm' => 'Ripristinare l\'ordinamento predefinito del menu?',
    'mnsort_reset_done' => 'Ripristinato predefinito',
    'mnsort_bad_data' => 'Dati di ordinamento non validi',
    'mnsort_log_update' => 'Ordinamento menu aggiornato',
    'mnsort_log_reset' => 'Ordinamento menu ripristinato',
    'mnsort_reset_msg' => 'Ordinamento predefinito ripristinato',
    'mnsort_grp_system' => 'Sistema',
    'mnsort_grp_setting' => 'Impostazioni del sito',
    'mnsort_grp_plugin' => 'Plugin',
    'mnsort_from_plugin' => 'Plugin: ',
];
