<?php
/**
 * YikaiCMS - Korean language pack (ko).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'mnsort_title' => '관리자 페이지 메뉴 정렬',
    'mnsort_tip' => '드래그하여 정렬, 이름을 클릭해 이름 변경, 👁로 표시/숨김 전환. :b변경 사항은 자동 저장되며:_b 관리자 페이지를 새로 고친 후 적용됩니다. 이름 변경은 현재 관리자 언어(:lang)에만 적용되며, 비우면 기본값으로 복원됩니다.',
    'mnsort_reset' => '기본값 복원',
    'mnsort_save_now' => '지금 저장',
    'mnsort_toggle_group' => '그룹 전체 표시/숨김',
    'mnsort_toggle_item' => '표시/숨김',
    'mnsort_rename_tip' => '이름을 바꾸면 즉시 저장됩니다. 비우면 기본값으로 복원됩니다.',
    'mnsort_saving' => '저장 중…',
    'mnsort_autosaved' => '✓ 자동 저장됨 ',
    'mnsort_saved_hint' => '저장되었습니다. 관리자 페이지를 새로 고치면 사이드바에 적용됩니다.',
    'mnsort_save_failed' => '저장 실패',
    'mnsort_reset_confirm' => '메뉴 순서를 기본값으로 복원할까요?',
    'mnsort_reset_done' => '기본값으로 복원됨',
    'mnsort_bad_data' => '유효하지 않은 정렬 데이터',
    'mnsort_log_update' => '메뉴 정렬 설정을 업데이트했습니다',
    'mnsort_log_reset' => '메뉴 정렬 초기화',
    'mnsort_reset_msg' => '기본 정렬로 복원되었습니다',
    'mnsort_grp_system' => '시스템',
    'mnsort_grp_setting' => '사이트 설정',
    'mnsort_grp_plugin' => '플러그인 관리',
    'mnsort_from_plugin' => '플러그인·',
];
