<?php
/**
 * YikaiCMS - Malay language pack (ms).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'mnsort_title' => 'Susunan Menu Pentadbir',
    'mnsort_tip' => 'Seret untuk menyusun semula, klik nama untuk menamakannya semula, dan gunakan 👁 untuk papar atau sembunyi — :b perubahan disimpan secara automatik :_b, dan berkuat kuasa selepas anda memuat semula halaman pentadbir. Penamaan semula hanya terpakai pada bahasa pentadbir semasa (:lang); kosongkan medan untuk memulihkan lalai.',
    'mnsort_reset' => 'Tetapkan semula kepada lalai',
    'mnsort_save_now' => 'Simpan sekarang',
    'mnsort_toggle_group' => 'Papar atau sembunyi keseluruhan kumpulan',
    'mnsort_toggle_item' => 'Papar atau sembunyi',
    'mnsort_rename_tip' => 'Penamaan semula disimpan serta-merta. Kosongkan medan untuk memulihkan lalai.',
    'mnsort_saving' => 'Menyimpan…',
    'mnsort_autosaved' => '✓ Disimpan ',
    'mnsort_saved_hint' => 'Disimpan. Muat semula halaman pentadbir untuk melihat bar sisi baharu.',
    'mnsort_save_failed' => 'Gagal menyimpan',
    'mnsort_reset_confirm' => 'Tetapkan semula susunan menu kepada lalai?',
    'mnsort_reset_done' => 'Tetapkan semula kepada lalai',
    'mnsort_bad_data' => 'Data susunan tidak sah',
    'mnsort_log_update' => 'Susunan menu dikemas kini',
    'mnsort_log_reset' => 'Susunan menu ditetapkan semula',
    'mnsort_reset_msg' => 'Susunan menu ditetapkan semula kepada lalai',
    'mnsort_grp_system' => 'Sistem',
    'mnsort_grp_setting' => 'Tetapan laman',
    'mnsort_grp_plugin' => 'Pemalam',
    'mnsort_from_plugin' => 'Pemalam: ',
];
