<?php
/**
 * YikaiCMS - Brazilian Portuguese language pack (pt).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'mnsort_title' => 'Ordenação dos menus do painel',
    'mnsort_tip' => 'Arraste para reordenar, clique no nome para renomear e use 👁 para exibir ou ocultar. :b As alterações são salvas automaticamente :_b e entram em vigor ao atualizar uma página do painel. A mudança de nome vale apenas para o idioma atual do painel (:lang). Limpe o campo para restaurar o padrão.',
    'mnsort_reset' => 'Restaurar padrão',
    'mnsort_save_now' => 'Salvar agora',
    'mnsort_toggle_group' => 'Exibir ou ocultar todo o grupo',
    'mnsort_toggle_item' => 'Exibir ou ocultar',
    'mnsort_rename_tip' => 'A mudança de nome é salva imediatamente. Limpe o campo para restaurar o padrão.',
    'mnsort_saving' => 'Salvando…',
    'mnsort_autosaved' => '✓ Salvo automaticamente ',
    'mnsort_saved_hint' => 'Salvo. Atualize uma página do painel para aplicar à barra lateral.',
    'mnsort_save_failed' => 'Não foi possível salvar',
    'mnsort_reset_confirm' => 'Restaurar a ordenação padrão dos menus?',
    'mnsort_reset_done' => 'Padrão restaurado',
    'mnsort_bad_data' => 'Dados de ordenação inválidos',
    'mnsort_log_update' => 'Configuração de ordenação dos menus atualizada',
    'mnsort_log_reset' => 'Ordenação dos menus redefinida',
    'mnsort_reset_msg' => 'Ordenação padrão restaurada',
    'mnsort_grp_system' => 'Sistema',
    'mnsort_grp_setting' => 'Configurações do site',
    'mnsort_grp_plugin' => 'Plugins',
    'mnsort_from_plugin' => 'Plugin: ',
];
