<?php
/**
 * YikaiCMS - Thai language pack (th).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'mnsort_title' => 'จัดเรียงเมนูแผงผู้ดูแลระบบ',
    'mnsort_tip' => 'ลากเพื่อจัดเรียง คลิกชื่อเพื่อเปลี่ยนชื่อ และใช้ 👁 สลับแสดง/ซ่อน :bการเปลี่ยนแปลงบันทึกอัตโนมัติ:_b และมีผลเมื่อรีเฟรชหน้าแผงผู้ดูแลระบบ การเปลี่ยนชื่อมีผลเฉพาะภาษาปัจจุบันของแผงผู้ดูแลระบบ (:lang) เว้นว่างเพื่อคืนค่าเริ่มต้น',
    'mnsort_reset' => 'คืนค่าเริ่มต้น',
    'mnsort_save_now' => 'บันทึกทันที',
    'mnsort_toggle_group' => 'แสดง/ซ่อนทั้งกลุ่ม',
    'mnsort_toggle_item' => 'แสดง/ซ่อน',
    'mnsort_rename_tip' => 'การเปลี่ยนชื่อบันทึกทันที เว้นว่างเพื่อคืนค่าเริ่มต้น',
    'mnsort_saving' => 'กำลังบันทึก…',
    'mnsort_autosaved' => '✓ บันทึกแล้ว ',
    'mnsort_saved_hint' => 'บันทึกแล้ว รีเฟรชหน้าแผงผู้ดูแลระบบเพื่อดูแถบด้านข้างใหม่',
    'mnsort_save_failed' => 'บันทึกไม่สำเร็จ',
    'mnsort_reset_confirm' => 'คืนค่าการจัดเรียงเมนูเป็นค่าเริ่มต้นหรือไม่',
    'mnsort_reset_done' => 'คืนค่าเริ่มต้นแล้ว',
    'mnsort_bad_data' => 'ข้อมูลการจัดเรียงไม่ถูกต้อง',
    'mnsort_log_update' => 'อัปเดตการจัดเรียงเมนู',
    'mnsort_log_reset' => 'รีเซ็ตการจัดเรียงเมนู',
    'mnsort_reset_msg' => 'คืนค่าการจัดเรียงเริ่มต้นแล้ว',
    'mnsort_grp_system' => 'ระบบ',
    'mnsort_grp_setting' => 'การตั้งค่าเว็บไซต์',
    'mnsort_grp_plugin' => 'ปลั๊กอิน',
    'mnsort_from_plugin' => 'ปลั๊กอิน: ',
];
