<?php
/**
 * YikaiCMS - Turkish language pack (tr).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'mnsort_title' => 'Yönetim Menüsü Sıralaması',
    'mnsort_tip' => 'Sıralamak için sürükleyin, yeniden adlandırmak için bir ada tıklayın ve göstermek/gizlemek için 👁 kullanın. :b Değişiklikler otomatik kaydedilir.:_b ve bir yönetim sayfası yenilendikten sonra etkili olur. Yeniden adlandırma yalnızca geçerli yönetim dilini etkiler (:lang); varsayılana dönmek için alanı temizleyin.',
    'mnsort_reset' => 'Varsayılana sıfırla',
    'mnsort_save_now' => 'Şimdi kaydet',
    'mnsort_toggle_group' => 'Tüm grubu göster veya gizle',
    'mnsort_toggle_item' => 'Göster veya gizle',
    'mnsort_rename_tip' => 'Yeniden adlandırma hemen kaydedilir. Varsayılana dönmek için alanı temizleyin.',
    'mnsort_saving' => 'Kaydediliyor…',
    'mnsort_autosaved' => '✓ Kaydedildi ',
    'mnsort_saved_hint' => 'Kaydedildi. Yeni kenar çubuğunu görmek için bir yönetim sayfasını yenileyin.',
    'mnsort_save_failed' => 'Kaydetme başarısız',
    'mnsort_reset_confirm' => 'Menü sırası varsayılana sıfırlansın mı?',
    'mnsort_reset_done' => 'Varsayılana sıfırlandı',
    'mnsort_bad_data' => 'Geçersiz sıralama verisi',
    'mnsort_log_update' => 'Menü sırası güncellendi',
    'mnsort_log_reset' => 'Menü sırası sıfırlandı',
    'mnsort_reset_msg' => 'Menü sırası varsayılana sıfırlandı',
    'mnsort_grp_system' => 'Sistem',
    'mnsort_grp_setting' => 'Site ayarları',
    'mnsort_grp_plugin' => 'Eklentiler',
    'mnsort_from_plugin' => 'Eklenti: ',
];
