<?php
/**
 * YikaiCMS - Vietnamese language pack (vi).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'mnsort_title' => 'Sắp xếp trình đơn trang quản trị',
    'mnsort_tip' => 'Kéo để sắp xếp, nhấp vào tên để đổi tên, dùng 👁 để ẩn/hiện — :b thay đổi được tự động lưu :_b và có hiệu lực sau khi bạn tải lại trang quản trị. Đổi tên chỉ áp dụng cho ngôn ngữ trang quản trị hiện tại (:lang); xóa trống để khôi phục mặc định.',
    'mnsort_reset' => 'Khôi phục mặc định',
    'mnsort_save_now' => 'Lưu ngay',
    'mnsort_toggle_group' => 'Ẩn/hiện cả nhóm',
    'mnsort_toggle_item' => 'Ẩn/hiện',
    'mnsort_rename_tip' => 'Đổi tên sẽ lưu ngay; xóa trống để khôi phục mặc định',
    'mnsort_saving' => 'Đang lưu…',
    'mnsort_autosaved' => '✓ Đã tự động lưu ',
    'mnsort_saved_hint' => 'Đã lưu. Tải lại trang quản trị để thanh bên cập nhật.',
    'mnsort_save_failed' => 'Lưu thất bại',
    'mnsort_reset_confirm' => 'Khôi phục thứ tự trình đơn mặc định?',
    'mnsort_reset_done' => 'Đã khôi phục mặc định',
    'mnsort_bad_data' => 'Dữ liệu sắp xếp không hợp lệ',
    'mnsort_log_update' => 'Đã cập nhật cấu hình sắp xếp trình đơn',
    'mnsort_log_reset' => 'Đặt lại sắp xếp trình đơn',
    'mnsort_reset_msg' => 'Đã khôi phục thứ tự mặc định',
    'mnsort_grp_system' => 'Hệ thống',
    'mnsort_grp_setting' => 'Cài đặt trang web',
    'mnsort_grp_plugin' => 'Quản lý plugin',
    'mnsort_from_plugin' => 'Plugin: ',
];
