<?php
/**
 * YikaiCMS - Arabic language pack (ar).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'stt_title' => 'دمج الإحصاءات',
    'stt_desc' => 'اختر مزوّد الإحصاءات وأدخل معرّف الموقع، وسيحقن النظام رمز الإحصاءات تلقائيًا في صفحة الموقع :head دون الحاجة إلى كتابة أي سكربت يدويًا.',
    'stt_provider' => 'مزوّد الإحصاءات',
    'stt_disabled' => 'معطّل',
    'stt_site_id' => 'معرّف الموقع',
    'stt_custom_code' => 'رمز إحصاءات مخصص',
    'stt_custom_warn' => '⚠ يُحقن في الصفحة كما هو، يرجى لصق الرمز من مصادر موثوقة فقط.',
    'stt_save' => 'حفظ',
    'stt_dashboard' => 'لوحة البيانات',
    'stt_pro_unlocked' => '✓ تم فتح Pro. يمكنك الانتقال إلى المزوّد المختار لعرض البيانات اللحظية، وستتوفر قريبًا لوحة بيانات داخل لوحة الإدارة تسحب اتجاهات PV/UV عبر API تلقائيًا.',
    'stt_open_console' => 'فتح لوحة بيانات :provider →',
    'stt_pick_first' => 'اختر أولًا أحد المزوّدين المعيّنين مسبقًا في الأعلى.',
    'stt_pro_pitch' => 'الترقية إلى :b Pro :_b لفتح لوحة البيانات في لوحة الإدارة: عرض اتجاهات PV / UV مباشرة دون تسجيل الدخول إلى منصة خارجية.',
    'stt_log_update' => 'تحديث إعدادات دمج الإحصاءات',
    'stt_p_baidu' => 'Baidu Tongji',
    'stt_p_51la' => '51.la Analytics',
    'stt_p_cnzz' => 'CNZZ / Umeng+',
    'stt_p_custom' => 'رمز مخصص',
    'stt_h_baidu' => 'الإدارة → الحصول على الرمز، فالسلسلة التي تلي hm.js?id= هي معرّف الموقع',
    'stt_h_51la' => 'المعرّف الرقمي الذي تحصل عليه بعد إنشاء الموقع',
    'stt_h_cnzz' => 'معرّف إحصاءات الموقع',
    'stt_h_ga4' => 'معرّف القياس بصيغة G-XXXXXXXXXX',
    'stt_h_custom' => 'الصق رمز الإحصاءات من الطرف الثالث مباشرة (يُحقن كما هو داخل <head>)',
    'stt_pro_badge' => 'Pro',
    'stt_go_license' => 'الانتقال إلى إدارة الترخيص →',
];
