<?php
/**
 * YikaiCMS - Spanish language pack (es).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'stt_title' => 'Estadísticas',
    'stt_desc' => 'Seleccione un proveedor de estadísticas e introduzca el ID del sitio. El sistema insertará automáticamente el código de seguimiento en :head del sitio web, sin necesidad de escribir scripts.',
    'stt_provider' => 'Proveedor de estadísticas',
    'stt_disabled' => 'Desactivado',
    'stt_site_id' => 'ID del sitio',
    'stt_custom_code' => 'Código de seguimiento personalizado',
    'stt_custom_warn' => '⚠ El código se inserta en la página sin modificarlo. Pegue solo código de fuentes de confianza.',
    'stt_save' => 'Guardar',
    'stt_dashboard' => 'Panel de estadísticas',
    'stt_pro_unlocked' => '✓ Pro está activado. Puede consultar los datos en tiempo real en el proveedor seleccionado. Próximamente habrá un panel en el panel de administración que obtendrá las tendencias PV/UV automáticamente mediante API.',
    'stt_open_console' => 'Abrir el panel de estadísticas de :provider →',
    'stt_pick_first' => 'Seleccione primero uno de los proveedores predefinidos de arriba.',
    'stt_pro_pitch' => 'Actualice a :b Pro :_b para activar el panel de estadísticas del panel de administración y ver directamente las tendencias PV / UV sin iniciar sesión en una plataforma externa.',
    'stt_log_update' => 'Se ha actualizado la configuración de estadísticas',
    'stt_p_baidu' => 'Baidu Tongji',
    'stt_p_51la' => 'Estadísticas 51.la',
    'stt_p_cnzz' => 'CNZZ / Umeng+',
    'stt_p_custom' => 'Código personalizado',
    'stt_h_baidu' => 'Administración → Obtener código. La cadena después de hm.js?id= es el ID del sitio.',
    'stt_h_51la' => 'El ID numérico obtenido al crear el sitio',
    'stt_h_cnzz' => 'ID de las estadísticas del sitio',
    'stt_h_ga4' => 'ID de medición con el formato G-XXXXXXXXXX',
    'stt_h_custom' => 'Pegue el código de estadísticas del proveedor externo (se insertará en <head> sin modificarlo)',
    'stt_pro_badge' => 'Pro',
    'stt_go_license' => 'Ir a Licencias →',
];
