<?php
/**
 * YikaiCMS - French language pack (fr).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'stt_title' => 'Statistiques',
    'stt_desc' => 'Choisissez un fournisseur et saisissez l’identifiant de votre site. Le code de suivi est automatiquement inséré dans le :head du site — aucun script à écrire à la main.',
    'stt_provider' => 'Fournisseur',
    'stt_disabled' => 'Désactivé',
    'stt_site_id' => 'Identifiant du site',
    'stt_custom_code' => 'Code de suivi personnalisé',
    'stt_custom_warn' => '⚠ Inséré tel quel dans la page. Collez uniquement du code provenant d’une source fiable.',
    'stt_save' => 'Enregistrer',
    'stt_dashboard' => 'Tableau de bord',
    'stt_pro_unlocked' => '✓ La version Pro est active. Ouvrez la plateforme de votre fournisseur pour consulter les chiffres en direct. Un tableau de bord dans l’administration affichant les tendances PV/UV via l’API est en préparation.',
    'stt_open_console' => 'Ouvrir :provider →',
    'stt_pick_first' => 'Choisissez d’abord l’un des fournisseurs prédéfinis ci-dessus.',
    'stt_pro_pitch' => 'Passez à la :b version Pro :_b pour consulter dans l’administration les tendances PV et UV sans vous connecter à une plateforme tierce.',
    'stt_log_update' => 'Réglages des statistiques mis à jour',
    'stt_p_baidu' => 'Baidu Tongji',
    'stt_p_51la' => 'Statistiques 51.la',
    'stt_p_cnzz' => 'CNZZ / Umeng+',
    'stt_p_custom' => 'Code personnalisé',
    'stt_h_baidu' => 'Administration → Obtenir le code ; la chaîne après hm.js?id= correspond à l’identifiant de votre site.',
    'stt_h_51la' => 'Identifiant numérique attribué à la création du site',
    'stt_h_cnzz' => 'Identifiant des statistiques du site',
    'stt_h_ga4' => 'Identifiant de mesure au format G-XXXXXXXXXX',
    'stt_h_custom' => 'Collez le code de suivi tiers ; il sera inséré tel quel dans <head>.',
    'stt_pro_badge' => 'Pro',
    'stt_go_license' => 'Accéder aux licences →',
];
