<?php
/**
 * YikaiCMS - Indonesian language pack (id).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'stt_title' => 'Integrasi analitik',
    'stt_desc' => 'Pilih penyedia dan masukkan ID situs; kode pelacakan akan otomatis disuntikkan ke :head halaman situs web, tanpa perlu menulis skrip sendiri.',
    'stt_provider' => 'Penyedia',
    'stt_disabled' => 'Nonaktif',
    'stt_site_id' => 'ID situs',
    'stt_custom_code' => 'Kode pelacakan kustom',
    'stt_custom_warn' => '⚠ Disuntikkan ke halaman apa adanya; tempelkan hanya kode dari sumber tepercaya.',
    'stt_save' => 'Simpan',
    'stt_dashboard' => 'Dasbor data',
    'stt_pro_unlocked' => '✓ Pro telah aktif. Buka penyedia pilihan Anda untuk melihat data real-time. Dasbor dalam panel admin yang menarik tren PV/UV melalui API akan segera hadir.',
    'stt_open_console' => 'Buka panel admin data :provider →',
    'stt_pick_first' => 'Pilih salah satu penyedia preset di atas terlebih dahulu.',
    'stt_pro_pitch' => 'Tingkatkan ke :b Pro :_b untuk membuka dasbor data di panel admin: lihat tren PV / UV langsung dari panel admin tanpa masuk ke platform pihak ketiga.',
    'stt_log_update' => 'Memperbarui pengaturan integrasi analitik',
    'stt_p_baidu' => 'Baidu Tongji',
    'stt_p_51la' => '51.la Analytics',
    'stt_p_cnzz' => 'CNZZ / Umeng+',
    'stt_p_custom' => 'Kode kustom',
    'stt_h_baidu' => 'Admin → Dapatkan kode; string setelah hm.js?id= adalah ID situs Anda',
    'stt_h_51la' => 'ID numerik yang Anda dapatkan setelah membuat situs',
    'stt_h_cnzz' => 'ID statistik situs Anda',
    'stt_h_ga4' => 'ID pengukuran, dalam bentuk G-XXXXXXXXXX',
    'stt_h_custom' => 'Tempelkan langsung kode pelacakan pihak ketiga (disuntikkan apa adanya ke <head>)',
    'stt_pro_badge' => 'Pro',
    'stt_go_license' => 'Buka manajemen lisensi →',
];
