<?php
/**
 * YikaiCMS - Italian language pack (it).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'stt_title' => 'Integrazione statistiche',
    'stt_desc' => 'Scegli un fornitore e inserisci l\'ID del sito. Il codice di tracciamento viene iniettato automaticamente nel :head del sito web — nessuno script scritto a mano.',
    'stt_provider' => 'Fornitore di statistiche',
    'stt_disabled' => 'Disattivato',
    'stt_site_id' => 'ID sito',
    'stt_custom_code' => 'Codice di tracciamento personalizzato',
    'stt_custom_warn' => '⚠ Iniettato nella pagina così com\'è. Incolla solo codice da una fonte attendibile.',
    'stt_save' => 'Salva',
    'stt_dashboard' => 'Pannello dati',
    'stt_pro_unlocked' => '✓ Pro attivo. Apri il fornitore scelto per i dati in tempo reale; un pannello di amministrazione che recupera le tendenze PV/UV tramite API è in arrivo.',
    'stt_open_console' => 'Apri il pannello di amministrazione di :provider →',
    'stt_pick_first' => 'Scegli prima uno dei fornitori predefiniti qui sopra.',
    'stt_pro_pitch' => 'Passa a :b Pro :_b per il pannello dati: tendenze PV / UV direttamente nel pannello di amministrazione, senza accedere a piattaforme di terze parti.',
    'stt_log_update' => 'Impostazioni statistiche aggiornate',
    'stt_p_baidu' => 'Baidu Analytics',
    'stt_p_51la' => '51.la Statistiche',
    'stt_p_cnzz' => 'CNZZ / Umeng+',
    'stt_p_custom' => 'Codice personalizzato',
    'stt_h_baidu' => 'Amministrazione → Ottieni codice; la stringa dopo hm.js?id= è l\'ID del sito',
    'stt_h_51la' => 'L\'ID numerico ottenuto dopo la creazione del sito',
    'stt_h_cnzz' => 'L\'ID delle statistiche del sito',
    'stt_h_ga4' => 'ID di misurazione, nel formato G-XXXXXXXXXX',
    'stt_h_custom' => 'Incolla il codice di tracciamento di terze parti (iniettato in <head> così com\'è)',
    'stt_pro_badge' => 'Pro',
    'stt_go_license' => 'Vai alla gestione della licenza →',
];
