<?php
/**
 * YikaiCMS - Korean language pack (ko).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'stt_title' => '통계 연동',
    'stt_desc' => '통계 서비스 제공자를 선택하고 사이트 ID를 입력하면 시스템이 통계 코드를 사이트 :head에 자동으로 삽입합니다. 스크립트를 직접 작성할 필요가 없습니다.',
    'stt_provider' => '통계 서비스 제공자',
    'stt_disabled' => '사용 안 함',
    'stt_site_id' => '사이트 ID',
    'stt_custom_code' => '사용자 정의 통계 코드',
    'stt_custom_warn' => '⚠ 페이지에 그대로 삽입되므로 신뢰할 수 있는 출처의 코드만 붙여 넣으세요.',
    'stt_save' => '저장',
    'stt_dashboard' => '데이터 대시보드',
    'stt_pro_unlocked' => '✓ 프로가 활성화되었습니다. 선택한 서비스 제공자에서 실시간 데이터를 확인할 수 있습니다. 관리자 페이지 API가 자동으로 대시보드를 불러오는 기능(PV/UV 추이)은 곧 출시됩니다.',
    'stt_open_console' => ':provider 데이터 관리자 페이지 열기 →',
    'stt_pick_first' => '먼저 위에서 사전 설정된 서비스 제공자를 하나 선택하세요.',
    'stt_pro_pitch' => ':b프로:_b로 업그레이드하면 관리자 페이지 데이터 대시보드가 열립니다. 제3자 플랫폼에 로그인할 필요 없이 관리자 페이지에서 바로 PV / UV 추이를 확인할 수 있습니다.',
    'stt_log_update' => '통계 연동 설정 업데이트',
    'stt_p_baidu' => '바이두 통계',
    'stt_p_51la' => '51.la 사이트 통계',
    'stt_p_cnzz' => 'CNZZ / 우멍+',
    'stt_p_custom' => '사용자 정의 코드',
    'stt_h_baidu' => '관리 → 코드 가져오기, hm.js?id= 뒤의 문자열이 사이트 ID입니다',
    'stt_h_51la' => '사이트를 생성한 후 받은 숫자 ID',
    'stt_h_cnzz' => '사이트 통계의 ID',
    'stt_h_ga4' => '측정 ID(예: G-XXXXXXXXXX)',
    'stt_h_custom' => '제3자 통계 코드를 직접 붙여 넣으세요(<head>에 그대로 삽입됩니다)',
    'stt_pro_badge' => '프로',
    'stt_go_license' => '라이선스 관리로 이동 →',
];
