<?php
/**
 * YikaiCMS - Malay language pack (ms).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'stt_title' => 'Analitik',
    'stt_desc' => 'Pilih pembekal dan masukkan ID laman anda. Kod penjejakan disuntik ke :head laman web secara automatik — tanpa perlu menulis skrip.',
    'stt_provider' => 'Pembekal',
    'stt_disabled' => 'Dilumpuhkan',
    'stt_site_id' => 'ID laman',
    'stt_custom_code' => 'Kod penjejakan tersuai',
    'stt_custom_warn' => '⚠ Disuntik ke halaman sebagaimana adanya. Hanya tampal kod daripada sumber yang anda percayai.',
    'stt_save' => 'Simpan',
    'stt_dashboard' => 'Papan pemuka',
    'stt_pro_unlocked' => '✓ Pro telah diaktifkan. Buka pembekal anda untuk angka masa nyata. Papan pemuka dalam panel pentadbir yang menarik trend PV/UV melalui API akan datang.',
    'stt_open_console' => 'Buka panel pentadbir :provider →',
    'stt_pick_first' => 'Pilih salah satu pembekal praset di atas dahulu.',
    'stt_pro_pitch' => 'Naik taraf kepada :b Pro :_b untuk papan pemuka dalam panel pentadbir: lihat trend PV / UV tanpa log masuk ke platform pihak ketiga.',
    'stt_log_update' => 'Tetapan analitik dikemas kini',
    'stt_p_baidu' => 'Baidu Tongji',
    'stt_p_51la' => '51.la Analytics',
    'stt_p_cnzz' => 'CNZZ / Umeng+',
    'stt_p_custom' => 'Kod tersuai',
    'stt_h_baidu' => 'Admin → Dapatkan kod; rentetan selepas hm.js?id= ialah ID laman anda',
    'stt_h_51la' => 'ID berangka yang anda peroleh selepas mencipta laman',
    'stt_h_cnzz' => 'ID statistik laman anda',
    'stt_h_ga4' => 'ID ukuran, dalam bentuk G-XXXXXXXXXX',
    'stt_h_custom' => 'Tampal kod penjejakan pihak ketiga; ia disuntik ke dalam <head> sebagaimana adanya',
    'stt_pro_badge' => 'Pro',
    'stt_go_license' => 'Pergi ke pengurusan lesen →',
];
