<?php
/**
 * YikaiCMS - Brazilian Portuguese language pack (pt).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'stt_title' => 'Análise de acesso',
    'stt_desc' => 'Selecione um serviço de análise e informe o ID do site. O sistema insere automaticamente o código de análise no :head das páginas públicas, sem precisar escrever scripts.',
    'stt_provider' => 'Serviço de análise',
    'stt_disabled' => 'Desativado',
    'stt_site_id' => 'ID do site',
    'stt_custom_code' => 'Código de análise personalizado',
    'stt_custom_warn' => '⚠ O código é inserido na página sem alterações. Cole apenas código de uma fonte confiável.',
    'stt_save' => 'Salvar',
    'stt_dashboard' => 'Painel de dados',
    'stt_pro_unlocked' => '✓ Pro desbloqueado. Acesse o serviço selecionado para ver dados em tempo real. O painel no CMS com tendências de PV/UV obtidas automaticamente por API estará disponível em breve.',
    'stt_open_console' => 'Abrir painel de dados de :provider →',
    'stt_pick_first' => 'Selecione primeiro um dos serviços predefinidos acima.',
    'stt_pro_pitch' => 'Atualize para :b Pro :_b para desbloquear o painel de dados no CMS e ver as tendências de PV / UV sem entrar em uma plataforma externa.',
    'stt_log_update' => 'Configurações de integração de análise atualizadas',
    'stt_p_baidu' => 'Baidu Tongji',
    'stt_p_51la' => '51.la Analytics',
    'stt_p_cnzz' => 'CNZZ / Umeng+',
    'stt_p_custom' => 'Código personalizado',
    'stt_h_baidu' => 'Administração → Obter código. O trecho após hm.js?id= é o ID do site.',
    'stt_h_51la' => 'O ID numérico recebido ao criar o site',
    'stt_h_cnzz' => 'ID das estatísticas do site',
    'stt_h_ga4' => 'ID de medição, no formato G-XXXXXXXXXX',
    'stt_h_custom' => 'Cole o código de análise de terceiros; ele é inserido em <head> sem alterações',
    'stt_pro_badge' => 'Pro',
    'stt_go_license' => 'Ir para Gerenciamento de licenças →',
];
