<?php
/**
 * YikaiCMS - Thai language pack (th).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'stt_title' => 'การเชื่อมต่อสถิติ',
    'stt_desc' => 'เลือกผู้ให้บริการสถิติและกรอก ID เว็บไซต์ ระบบจะแทรกโค้ดสถิติลงในหน้าเว็บโดยอัตโนมัติที่ :head โดยไม่ต้องเขียนสคริปต์เอง',
    'stt_provider' => 'ผู้ให้บริการสถิติ',
    'stt_disabled' => 'ไม่เปิดใช้งาน',
    'stt_site_id' => 'ID เว็บไซต์',
    'stt_custom_code' => 'โค้ดสถิติแบบกำหนดเอง',
    'stt_custom_warn' => '⚠ แทรกเข้าไปในหน้าตามที่เป็นอยู่ โปรดวางเฉพาะโค้ดจากแหล่งที่เชื่อถือได้',
    'stt_save' => 'บันทึก',
    'stt_dashboard' => 'แดชบอร์ดข้อมูล',
    'stt_pro_unlocked' => '✓ ปลดล็อก Pro แล้ว คุณสามารถไปที่ผู้ให้บริการที่เลือกเพื่อดูข้อมูลเรียลไทม์ แดชบอร์ดในแผงผู้ดูแลระบบที่ดึงแนวโน้ม PV/UV ผ่าน API โดยอัตโนมัติกำลังจะเปิดตัว',
    'stt_open_console' => 'เปิดแผงข้อมูลของ :provider →',
    'stt_pick_first' => 'เลือกผู้ให้บริการสำเร็จรูปด้านบนก่อน',
    'stt_pro_pitch' => 'อัปเกรดเป็น :b Pro :_b เพื่อปลดล็อกแดชบอร์ดข้อมูลในแผงผู้ดูแลระบบ ดูแนวโน้ม PV / UV ได้โดยตรงโดยไม่ต้องเข้าสู่ระบบแพลตฟอร์มภายนอก',
    'stt_log_update' => 'อัปเดตการกำหนดค่าการเชื่อมต่อสถิติ',
    'stt_p_baidu' => 'Baidu Tongji',
    'stt_p_51la' => '51.la Analytics',
    'stt_p_cnzz' => 'CNZZ / Umeng+',
    'stt_p_custom' => 'โค้ดกำหนดเอง',
    'stt_h_baidu' => 'จัดการ → รับโค้ด สตริงที่อยู่หลัง hm.js?id= คือ ID เว็บไซต์ของคุณ',
    'stt_h_51la' => 'ID ตัวเลขที่ได้หลังจากสร้างเว็บไซต์',
    'stt_h_cnzz' => 'ID สถิติของเว็บไซต์ของคุณ',
    'stt_h_ga4' => 'Measurement ID ในรูปแบบ G-XXXXXXXXXX',
    'stt_h_custom' => 'วางโค้ดสถิติของบุคคลที่สามโดยตรง (แทรกเข้าไปใน <head> ตามที่เป็นอยู่)',
    'stt_pro_badge' => 'Pro',
    'stt_go_license' => 'ไปที่การจัดการสิทธิ์การใช้งาน →',
];
