<?php
/**
 * YikaiCMS - Turkish language pack (tr).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'stt_title' => 'Analitik',
    'stt_desc' => 'Bir sağlayıcı seçin ve site kimliğinizi girin. İzleme kodu web sitesi sayfalarının :head bölümüne otomatik olarak eklenir; elle yazılmış bir betik gerekmez.',
    'stt_provider' => 'Sağlayıcı',
    'stt_disabled' => 'Devre dışı',
    'stt_site_id' => 'Site kimliği',
    'stt_custom_code' => 'Özel izleme kodu',
    'stt_custom_warn' => '⚠ Sayfaya olduğu gibi eklenir. Yalnızca güvendiğiniz bir kaynaktan kod yapıştırın.',
    'stt_save' => 'Kaydet',
    'stt_dashboard' => 'Gösterge paneli',
    'stt_pro_unlocked' => '✓ Pro etkin. Canlı veriler için sağlayıcınızı açın. API üzerinden PV/UV eğilimlerini çeken yönetim paneli içi gösterge paneli yakında geliyor.',
    'stt_open_console' => ':provider veri yönetim panelini aç →',
    'stt_pick_first' => 'Önce yukarıdaki hazır sağlayıcılardan birini seçin.',
    'stt_pro_pitch' => ':b Pro :_b ile yönetim paneli içi gösterge panelinin kilidini açın: üçüncü taraf bir platforma giriş yapmadan PV / UV eğilimlerini doğrudan yönetim panelinden görün.',
    'stt_log_update' => 'Analitik ayarları güncellendi',
    'stt_p_baidu' => 'Baidu Tongji',
    'stt_p_51la' => '51.la Web Analizi',
    'stt_p_cnzz' => 'CNZZ / Umeng+',
    'stt_p_custom' => 'Özel kod',
    'stt_h_baidu' => 'Yönetim → Kodu al; hm.js?id= sonrasındaki dize site kimliğinizdir',
    'stt_h_51la' => 'Site oluşturduktan sonra aldığınız sayısal kimlik',
    'stt_h_cnzz' => 'Site istatistikleri kimliğiniz',
    'stt_h_ga4' => 'G-XXXXXXXXXX biçiminde ölçüm kimliği',
    'stt_h_custom' => 'Üçüncü taraf izleme kodunu yapıştırın; <head> içine olduğu gibi eklenir',
    'stt_pro_badge' => 'Pro',
    'stt_go_license' => 'Lisans yönetimine git →',
];
