<?php
/**
 * YikaiCMS - Vietnamese language pack (vi).
 * Generated by tools/i18n/merge.php from reviewed machine translations; keys follow lang/zh-CN.php.
 */

return [
    'stt_title' => 'Tích hợp thống kê',
    'stt_desc' => 'Chọn nhà cung cấp dịch vụ thống kê và điền ID trang web, hệ thống sẽ tự động chèn mã thống kê vào :head của trang web, không cần viết script thủ công.',
    'stt_provider' => 'Nhà cung cấp dịch vụ thống kê',
    'stt_disabled' => 'Không bật',
    'stt_site_id' => 'ID trang web',
    'stt_custom_code' => 'Mã thống kê tùy chỉnh',
    'stt_custom_warn' => '⚠ Chèn nguyên trạng vào trang, vui lòng chỉ dán mã từ nguồn đáng tin cậy.',
    'stt_save' => 'Lưu',
    'stt_dashboard' => 'Bảng điều khiển dữ liệu',
    'stt_pro_unlocked' => '✓ Pro đã được mở khóa. Bạn có thể đến nhà cung cấp đã chọn để xem dữ liệu thời gian thực; bảng điều khiển tự động kéo dữ liệu qua API trong trang quản trị (xu hướng PV/UV) sắp ra mắt.',
    'stt_open_console' => 'Mở trang quản trị dữ liệu :provider →',
    'stt_pick_first' => 'Trước tiên hãy chọn một nhà cung cấp đặt trước ở phía trên.',
    'stt_pro_pitch' => 'Nâng cấp lên :b Pro :_b để mở khóa bảng điều khiển dữ liệu trong trang quản trị: không cần đăng nhập nền tảng bên thứ ba, trực tiếp xem xu hướng PV / UV trong trang quản trị.',
    'stt_log_update' => 'Cập nhật cấu hình tích hợp thống kê',
    'stt_p_baidu' => 'Thống kê Baidu',
    'stt_p_51la' => 'Thống kê trang web 51.la',
    'stt_p_cnzz' => 'CNZZ / Umeng+',
    'stt_p_custom' => 'Mã tùy chỉnh',
    'stt_h_baidu' => 'Quản lý → Lấy mã, chuỗi sau hm.js?id= chính là ID trang web',
    'stt_h_51la' => 'ID dạng số nhận được sau khi tạo trang web',
    'stt_h_cnzz' => 'ID thống kê trang web',
    'stt_h_ga4' => 'ID đo lường, có dạng G-XXXXXXXXXX',
    'stt_h_custom' => 'Dán trực tiếp mã thống kê của bên thứ ba (chèn nguyên trạng vào <head>)',
    'stt_pro_badge' => 'Pro',
    'stt_go_license' => 'Đến quản lý giấy phép →',
];
