<?php
/**
 * YikaiCMS - Traditional Chinese (Taiwan) language pack (zh-TW).
 * Generated by tools/i18n/zh-tw.php from zh-CN via OpenCC; reviewed wording is kept while the zh-CN source is unchanged.
 * Content is not here: it stays in Simplified Chinese and the front end converts each page.
 */

return [
    'stt_title' => '統計接入',
    'stt_desc' => '選擇統計服務商並填寫網站 ID，系統會自動把統計程式碼注入前台頁面 :head，無需手寫指令碼。',
    'stt_provider' => '統計服務商',
    'stt_disabled' => '不啟用',
    'stt_site_id' => '網站 ID',
    'stt_custom_code' => '自定義統計程式碼',
    'stt_custom_warn' => '⚠ 原樣注入頁面，請僅貼上可信來源的程式碼。',
    'stt_save' => '儲存',
    'stt_dashboard' => '資料看板',
    'stt_pro_unlocked' => '✓ 專業版已解鎖。可前往所選服務商檢視即時資料，後台 API 自動回拉看板（PV/UV 趨勢）即將上線。',
    'stt_open_console' => '開啟 :provider 資料後台 →',
    'stt_pick_first' => '先在上方選擇一個預設服務商。',
    'stt_pro_pitch' => '升級:b專業版:_b解鎖後台資料看板：無需登入第三方平臺，直接在後台檢視 PV / UV 趨勢。',
    'stt_log_update' => '更新統計接入配置',
    'stt_p_baidu' => '百度統計',
    'stt_p_51la' => '51.la 網站統計',
    'stt_p_cnzz' => 'CNZZ / 友盟+',
    'stt_p_custom' => '自定義程式碼',
    'stt_h_baidu' => '管理 → 程式碼獲取，hm.js?id= 後面那串即網站 ID',
    'stt_h_51la' => '建立網站後得到的數字 ID',
    'stt_h_cnzz' => '網站統計的 ID',
    'stt_h_ga4' => '衡量 ID，形如 G-XXXXXXXXXX',
    'stt_h_custom' => '直接貼上第三方統計程式碼（原樣注入 <head>）',
    'stt_pro_badge' => '專業版',
    'stt_go_license' => '前往授權管理 →',
];
